# KDDCUP Data Extract

2017-05-11

### 录入数据

In [4]:
import numpy as np
import pandas as pd
from datetime import datetime,timedelta,date,time
import copy

In [5]:
# 读入平均时间，流量和天气数据（平均时间和流量由aggregate_travel_time.py和aggregate_volume.py生成）
travel_time_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/train_20min_avg_travel_time.csv'
volume_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/train_20min_avg_volume.csv'
weather_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/原始数据/weather_train.csv'
test_travel_time_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/test_20min_avg_travel_time.csv'
test_volume_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/test_20min_avg_volume.csv'
test_weather_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/原始数据/weather_test.csv'

raw_data = pd.read_csv(travel_time_infile)
raw_data2 = pd.read_csv(volume_infile)
weather_data = pd.read_csv(weather_infile)

In [15]:
# 训练集缺失值补充，保证每一个时间段都有数据
full_time = pd.read_csv('full_time.csv')
full_time = full_time.sort(['intersection_id','tollgate_id'])
raw_data = pd.merge(full_time, raw_data, on=['intersection_id','tollgate_id','time_window'], how='left')
ffill = lambda g:g.fillna(method='ffill')
bfill = lambda g:g.fillna(method='bfill')

raw_data['avg_travel_time'] = raw_data.groupby(['intersection_id','tollgate_id'])['avg_travel_time'].apply(ffill)
raw_data['avg_travel_time'] = raw_data.groupby(['intersection_id','tollgate_id'])['avg_travel_time'].apply(bfill)

full_time2 = pd.read_csv('full_time2.csv')
full_time2 = full_time2.sort(['tollgate_id','direction'])
raw_data2 = pd.merge(full_time2, raw_data2, on=['tollgate_id','time_window','direction'], how='left')
raw_data2['volume'] = raw_data2.groupby(['tollgate_id','direction'])['volume'].apply(ffill)
raw_data2['volume'] = raw_data2.groupby(['tollgate_id','direction'])['volume'].apply(bfill)

/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()
/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:12: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

### 先填补天气的缺失值

In [41]:
# 10.10号的用10.09和10.11的平均
date9_weather_data = weather_data[weather_data['date'] == '2016-10-09']
date11_weather_data = weather_data[weather_data['date'] == '2016-10-11']

date10_weather_data = date11_weather_data.copy()
date10_weather_data['date'] = '2016-10-10'
date10_weather_data['pressure'] = (date9_weather_data['pressure'].values + date11_weather_data['pressure'].values) / 2
date10_weather_data['sea_pressure'] = (date9_weather_data['sea_pressure'].values + date11_weather_data['sea_pressure'].values) / 2
date10_weather_data['wind_direction'] = (date9_weather_data['wind_direction'].values + date11_weather_data['wind_direction'].values) / 2
date10_weather_data['wind_speed'] = (date9_weather_data['wind_speed'].values + date11_weather_data['wind_speed'].values) / 2
date10_weather_data['temperature'] = (date9_weather_data['temperature'].values + date11_weather_data['temperature'].values) / 2
date10_weather_data['rel_humidity'] = (date9_weather_data['rel_humidity'].values + date11_weather_data['rel_humidity'].values) / 2
date10_weather_data['precipitation'] = (date9_weather_data['precipitation'].values + date11_weather_data['precipitation'].values) / 2

weather_data = pd.concat([weather_data, date10_weather_data], axis=0)

weather_data.index = np.arange(len(weather_data))

### 提取平均时间数据

In [6]:
# 整合平均时间与天气数据
raw_data['start_time'] = raw_data['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:], '%Y-%m-%d %H:%M:%S'))
weather_data['date'] = weather_data['date'].astype(str)
weather_data['hour'] = weather_data['hour'].map(lambda x: ' ' + time(x, 0, 0).strftime('%H:%M:%S'))
weather_data['start_time'] = weather_data['date'] + weather_data['hour']
weather_data['start_time'] = weather_data['start_time'].map(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
del weather_data['date']
del weather_data['hour']
num = len(weather_data)
for i in range(num):
    temp = weather_data.ix[i]
    temp1 = copy.deepcopy(temp)
    temp2 = copy.deepcopy(temp)
    temp3 = copy.deepcopy(temp)
    temp4 = copy.deepcopy(temp)
    temp5 = copy.deepcopy(temp)
    temp6 = copy.deepcopy(temp)
    temp7 = copy.deepcopy(temp)
    temp8 = copy.deepcopy(temp)
    stime = temp.start_time
    temp1.start_time = stime + timedelta(minutes=20)
    temp2.start_time = stime + timedelta(minutes=40)
    temp3.start_time = stime + timedelta(minutes=60)
    temp4.start_time = stime + timedelta(minutes=80)
    temp5.start_time = stime + timedelta(minutes=100)
    temp6.start_time = stime + timedelta(minutes=120)
    temp7.start_time = stime + timedelta(minutes=140)
    temp8.start_time = stime + timedelta(minutes=160)
    alltemp = [temp1, temp2, temp3, temp4, temp5, temp6, temp7, temp8]
    alltemp = pd.DataFrame(alltemp)
    weather_data = pd.concat([weather_data, alltemp])
# 合并
process_data = pd.merge(raw_data, weather_data, on='start_time', how='left')
process_data['time'] = process_data['start_time'].map(lambda x: x.time())
# 天气缺失补充
process_data.fillna(method='ffill', inplace=True)

process_data['date'] = process_data['start_time'].map(lambda x: x.date())

In [7]:
# 增加路线和星期几，小时，分钟
process_data['weekday'] = process_data['start_time'].map(lambda x: x.weekday())
process_data['hour'] = process_data['start_time'].map(lambda x: x.hour)
process_data['minute'] = process_data['start_time'].map(lambda x: x.minute)
process_data['route'] = process_data['intersection_id'].astype(str) + '-' + process_data['tollgate_id'].astype(str)

In [8]:
# 增加前20分钟平均时间特征
start_time = process_data['start_time']
avg_travel_time = process_data['avg_travel_time']

In [9]:
process_data

,intersection_id,tollgate_id,time_window,avg_travel_time,start_time,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,time,date,weekday,hour,minute,route
0,B,3,"[2016-07-19 00:00:00,2016-07-19 00:20:00)",70.85,2016-07-19 00:00:00,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,00:00:00,2016-07-19,1,0,0,B-3
1,B,3,"[2016-07-19 00:20:00,2016-07-19 00:40:00)",148.79,2016-07-19 00:20:00,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,00:20:00,2016-07-19,1,0,20,B-3
2,B,3,"[2016-07-19 01:40:00,2016-07-19 02:00:00)",93.72,2016-07-19 01:40:00,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,01:40:00,2016-07-19,1,1,40,B-3
3,B,3,"[2016-07-19 02:00:00,2016-07-19 02:20:00)",67.81,2016-07-19 02:00:00,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,02:00:00,2016-07-19,1,2,0,B-3
4,B,3,"[2016-07-19 02:40:00,2016-07-19 03:00:00)",167.55,2016-07-19 02:40:00,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,02:40:00,2016-07-19,1,2,40,B-3
5,B,3,"[2016-07-19 03:40:00,2016-07-19 04:00:00)",98.49,2016-07-19 03:40:00,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,03:40:00,2016-07-19,1,3,40,B-3
6,B,3,"[2016-07-19 04:00:00,2016-07-19 04:20:00)",96.67,2016-07-19 04:00:00,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:00:00,2016-07-19,1,4,0,B-3
7,B,3,"[2016-07-19 04:20:00,2016-07-19 04:40:00)",53.15,2016-07-19 04:20:00,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:20:00,2016-07-19,1,4,20,B-3
8,B,3,"[2016-07-19 04:40:00,2016-07-19 05:00:00)",55.25,2016-07-19 04:40:00,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:40:00,2016-07-19,1,4,40,B-3
9,B,3,"[2016-07-19 05:00:00,2016-07-19 05:20:00)",209.66,2016-07-19 05:00:00,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,05:00:00,2016-07-19,1,5,0,B-3
10,B,3,"[2016-07-19 06:00:00,2016-07-19 06:20:00)",145.94,2016-07-19 06:00:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:00:00,2016-07-19,1,6,0,B-3
11,B,3,"[2016-07-19 06:20:00,2016-07-19 06:40:00)",127.35,2016-07-19 06:20:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:20:00,2016-07-19,1,6,20,B-3
12,B,3,"[2016-07-19 06:40:00,2016-07-19 07:00:00)",97.20,2016-07-19 06:40:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:40:00,2016-07-19,1,6,40,B-3
13,B,3,"[2016-07-19 07:00:00,2016-07-19 07:20:00)",118.43,2016-07-19 07:00:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:00:00,2016-07-19,1,7,0,B-3
14,B,3,"[2016-07-19 07:20:00,2016-07-19 07:40:00)",82.63,2016-07-19 07:20:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:20:00,2016-07-19,1,7,20,B-3
15,B,3,"[2016-07-19 07:40:00,2016-07-19 08:00:00)",110.50,2016-07-19 07:40:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:40:00,2016-07-19,1,7,40,B-3
16,B,3,"[2016-07-19 08:00:00,2016-07-19 08:20:00)",125.76,2016-07-19 08:00:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:00:00,2016-07-19,1,8,0,B-3
17,B,3,"[2016-07-19 08:20:00,2016-07-19 08:40:00)",141.33,2016-07-19 08:20:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:20:00,2016-07-19,1,8,20,B-3
18,B,3,"[2016-07-19 08:40:00,2016-07-19 09:00:00)",176.08,2016-07-19 08:40:00,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:40:00,2016-07-19,1,8,40,B-3
19,B,3,"[2016-07-19 09:00:00,2016-07-19 09:20:00)",165.29,2016-07-19 09:00:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:00:00,2016-07-19,1,9,0,B-3
20,B,3,"[2016-07-19 09:20:00,2016-07-19 09:40:00)",78.13,2016-07-19 09:20:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:20:00,2016-07-19,1,9,20,B-3
21,B,3,"[2016-07-19 09:40:00,2016-07-19 10:00:00)",117.83,2016-07-19 09:40:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:40:00,2016-07-19,1,9,40,B-3
22,B,3,"[2016-07-19 10:00:00,2016-07-19 10:20:00)",98.92,2016-07-19 10:00:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,10:00:00,2016-07-19,1,10,0,B-3
23,B,3,"[2016-07-19 10:20:00,2016-07-19 10:40:00)",113.00,2016-07-19 10:20:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,10:20:00,2016-07-19,1,10,20,B-3
24,B,3,"[2016-07-19 10:40:00,2016-07-19 11:00:00)",98.15,2016-07-19 10:40:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,10:40:00,2016-07-19,1,10,40,B-3
25,B,3,"[2016-07-19 11:00:00,2016-07-19 11:20:00)",95.98,2016-07-19 11:00:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,11:00:00,2016-07-19,1,11,0,B-3
26,B,3,"[2016-07-19 11:20:00,2016-07-19 11:40:00)",84.36,2016-07-19 11:20:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,11:20:00,2016-07-19,1,11,20,B-3
27,B,3,"[2016-07-19 11:40:00,2016-07-19 12:00:00)",96.54,2016-07-19 11:40:00,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,11:40:00,2016-07-19,1,11,40,B-3
28,B,3,"[2016-07-19 12:00:00,2016-07-19 12:20:00)",144.87,2016-07-19 12:00:00,1000.2,1005.0,215.0,0.7,30.0,77.0,0.0,12:00:00,2016-07-19,1,12,0,B-3
29,B,3,"[2016-07-19 12:20:00,2016-07-19 12:40:00)",136.36,2016-07-19 12:20:00,1000.2,1005.0,215.0,0.7,30.0,77.0,0.0,12:20:00,2016-07-19,1,12,20,B-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27282,C,1,"[2016-10-24 10:20:00,2016-10-24 10:40:00)",189.94,2016-10-24 10:20:00,1007.3,1012.3,133.0,0.9,23.5,79.0,0.0,10:20:00,2016-10-24,0,10,20,C-1
27283,C,1,"[2016-10-24 10:40:00,2016-10-24 11:00:00)",140.88,2016-10-24 10:40:00,1007.3,1012.3,133.0,0.9,23.5,79.0,0.0,10:40:00,2016-10-24,0,10,40,C-1
27284,C,1,"[2016-10-24 11:00:00,2016-10-24 11:20:00)",161.66,2016-10-24 11:00:00,1007.3,1012.3,133.0,0.9,23.5,79.0,0.0,11:00:00,2016-10-24,0,11,0,C-1
27285,C,1,"[2016-10-24 11:20:00,2016-10-24 11:40:00)",158.37,2016-10-24 11:20:00,1007.3,1012.3,133.0,0.9,23.5,79.0,0.0,11:20:00,2016-10-24,0,11,20,C-1
27286,C,1,"[2016-10-24 11:40:00,2016-10-24 12:00:00)",193.82,2016-10-24 11:40:00,1007.3,1012.3,133.0,0.9,23.5,79.0,0.0,11:40:00,2016-10-24,0,11,40,C-1
27287,C,1,"[2016-10-24 12:00:00,2016-10-24 12:20:00)",172.15,2016-10-24 12:00:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,12:00:00,2016-10-24,0,12,0,C-1
27288,C,1,"[2016-10-24 12:20:00,2016-10-24 12:40:00)",139.68,2016-10-24 12:20:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,12:20:00,2016-10-24,0,12,20,C-1
27289,C,1,"[2016-10-24 12:40:00,2016-10-24 13:00:00)",142.81,2016-10-24 12:40:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,12:40:00,2016-10-24,0,12,40,C-1
27290,C,1,"[2016-10-24 13:00:00,2016-10-24 13:20:00)",158.07,2016-10-24 13:00:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,13:00:00,2016-10-24,0,13,0,C-1
27291,C,1,"[2016-10-24 13:20:00,2016-10-24 13:40:00)",201.41,2016-10-24 13:20:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,13:20:00,2016-10-24,0,13,20,C-1
27292,C,1,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",232.22,2016-10-24 14:00:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,14:00:00,2016-10-24,0,14,0,C-1
27293,C,1,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",171.23,2016-10-24 14:40:00,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0,14:40:00,2016-10-24,0,14,40,C-1
27294,C,1,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",168.85,2016-10-24 15:00:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,15:00:00,2016-10-24,0,15,0,C-1
27295,C,1,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",202.64,2016-10-24 15:20:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,15:20:00,2016-10-24,0,15,20,C-1
27296,C,1,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",175.87,2016-10-24 15:40:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,15:40:00,2016-10-24,0,15,40,C-1
27297,C,1,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",181.69,2016-10-24 16:00:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,16:00:00,2016-10-24,0,16,0,C-1
27298,C,1,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",188.64,2016-10-24 16:20:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,16:20:00,2016-10-24,0,16,20,C-1
27299,C,1,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",159.58,2016-10-24 16:40:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,16:40:00,2016-10-24,0,16,40,C-1
27300,C,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",190.15,2016-10-24 17:00:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,17:00:00,2016-10-24,0,17,0,C-1
27301,C,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",154.65,2016-10-24 17:20:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,17:20:00,2016-10-24,0,17,20,C-1
27302,C,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",160.04,2016-10-24 17:40:00,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0,17:40:00,2016-10-24,0,17,40,C-1
27303,C,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",271.20,2016-10-24 18:00:00,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0,18:00:00,2016-10-24,0,18,0,C-1
27304,C,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",260.35,2016-10-24 18:20:00,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0,18:20:00,2016-10-24,0,18,20,C-1
27305,C,1,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",206.34,2016-10-24 19:00:00,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0,19:00:00,2016-10-24,0,19,0,C-1
27306,C,1,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",215.99,2016-10-24 19:20:00,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0,19:20:00,2016-10-24,0,19,20,C-1
27307,C,1,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",148.62,2016-10-24 20:00:00,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0,20:00:00,2016-10-24,0,20,0,C-1
27308,C,1,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",115.50,2016-10-24 21:00:00,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0,21:00:00,2016-10-24,0,21,0,C-1
27309,C,1,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",133.45,2016-10-24 21:20:00,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0,21:20:00,2016-10-24,0,21,20,C-1
27310,C,1,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",153.95,2016-10-24 22:20:00,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0,22:20:00,2016-10-24,0,22,20,C-1
27311,C,1,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",236.09,2016-10-24 22:40:00,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0,22:40:00,2016-10-24,0,22,40,C-1

In [10]:
last_20min = process_data['avg_travel_time'].copy() 
last_40min = process_data['avg_travel_time'].copy()
last_60min = process_data['avg_travel_time'].copy()
last_80min = process_data['avg_travel_time'].copy()
last_100min = process_data['avg_travel_time'].copy()
last_120min = process_data['avg_travel_time'].copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(start_time)):
    cur_time = start_time[i] #当前时间
    # 前20min
    if (i-1) >= 0:
        last20 = cur_time - timedelta(minutes=20)
        if last20 == start_time[i-1]:
            last_20min[i] = avg_travel_time[i-1]
    # 前40min
    if (i-2) >= 0:
        last40 = cur_time - timedelta(minutes=40)
        for j in range(2):
            if last40 == start_time[i-j-1]:
                last_40min[i] = avg_travel_time[i-j-1]
                break
    # 前60min
    if (i-3) >= 0:
        last60 = cur_time - timedelta(minutes=60)
        for j in range(3):
            if last60 == start_time[i-j-1]:
                last_60min[i] = avg_travel_time[i-j-1]
                break
    # 前80min
    if (i-4) >= 0:
        last80 = cur_time - timedelta(minutes=80)
        for j in range(4):
            if last80 == start_time[i-j-1]:
                last_80min[i] = avg_travel_time[i-j-1]
                break
    # 前100min
    if (i-5) >= 0:
        last100 = cur_time - timedelta(minutes=100)
        for j in range(5):
            if last100 == start_time[i-j-1]:
                last_100min[i] = avg_travel_time[i-j-1]
                break
    # 前120min
    if (i-6) >= 0:
        last120 = cur_time - timedelta(minutes=120)
        for j in range(6):
            if last120 == start_time[i-j-1]:
                last_120min[i] = avg_travel_time[i-j-1]
                break

process_data['last_20min'] = last_20min
process_data['last_40min'] = last_40min
process_data['last_60min'] = last_60min
process_data['last_80min'] = last_80min
process_data['last_100min'] = last_100min
process_data['last_120min'] = last_120min

In [11]:
process_data

,intersection_id,tollgate_id,time_window,avg_travel_time,start_time,pressure,sea_pressure,wind_direction,wind_speed,temperature,...,weekday,hour,minute,route,last_20min,last_40min,last_60min,last_80min,last_100min,last_120min
0,B,3,"[2016-07-19 00:00:00,2016-07-19 00:20:00)",70.85,2016-07-19 00:00:00,1000.9,1005.8,219.0,3.3,27.5,...,1,0,0,B-3,NaN,NaN,NaN,NaN,NaN,NaN
1,B,3,"[2016-07-19 00:20:00,2016-07-19 00:40:00)",148.79,2016-07-19 00:20:00,1000.9,1005.8,219.0,3.3,27.5,...,1,0,20,B-3,70.85,NaN,NaN,NaN,NaN,NaN
2,B,3,"[2016-07-19 01:40:00,2016-07-19 02:00:00)",93.72,2016-07-19 01:40:00,1000.9,1005.8,219.0,3.3,27.5,...,1,1,40,B-3,NaN,NaN,NaN,NaN,NaN,NaN
3,B,3,"[2016-07-19 02:00:00,2016-07-19 02:20:00)",67.81,2016-07-19 02:00:00,1000.9,1005.8,219.0,3.3,27.5,...,1,2,0,B-3,93.72,NaN,NaN,NaN,NaN,NaN
4,B,3,"[2016-07-19 02:40:00,2016-07-19 03:00:00)",167.55,2016-07-19 02:40:00,1000.9,1005.8,219.0,3.3,27.5,...,1,2,40,B-3,NaN,67.81,93.72,NaN,NaN,NaN
5,B,3,"[2016-07-19 03:40:00,2016-07-19 04:00:00)",98.49,2016-07-19 03:40:00,1000.5,1005.3,212.0,3.8,31.7,...,1,3,40,B-3,NaN,NaN,167.55,NaN,67.81,NaN
6,B,3,"[2016-07-19 04:00:00,2016-07-19 04:20:00)",96.67,2016-07-19 04:00:00,1000.5,1005.3,212.0,3.8,31.7,...,1,4,0,B-3,98.49,NaN,NaN,167.55,NaN,67.81
7,B,3,"[2016-07-19 04:20:00,2016-07-19 04:40:00)",53.15,2016-07-19 04:20:00,1000.5,1005.3,212.0,3.8,31.7,...,1,4,20,B-3,96.67,98.49,NaN,NaN,167.55,NaN
8,B,3,"[2016-07-19 04:40:00,2016-07-19 05:00:00)",55.25,2016-07-19 04:40:00,1000.5,1005.3,212.0,3.8,31.7,...,1,4,40,B-3,53.15,96.67,98.49,NaN,NaN,167.55
9,B,3,"[2016-07-19 05:00:00,2016-07-19 05:20:00)",209.66,2016-07-19 05:00:00,1000.5,1005.3,212.0,3.8,31.7,...,1,5,0,B-3,55.25,53.15,96.67,98.49,NaN,NaN
10,B,3,"[2016-07-19 06:00:00,2016-07-19 06:20:00)",145.94,2016-07-19 06:00:00,999.7,1004.5,239.0,1.9,31.8,...,1,6,0,B-3,NaN,NaN,209.66,55.25,53.15,96.67
11,B,3,"[2016-07-19 06:20:00,2016-07-19 06:40:00)",127.35,2016-07-19 06:20:00,999.7,1004.5,239.0,1.9,31.8,...,1,6,20,B-3,145.94,NaN,NaN,209.66,55.25,53.15
12,B,3,"[2016-07-19 06:40:00,2016-07-19 07:00:00)",97.20,2016-07-19 06:40:00,999.7,1004.5,239.0,1.9,31.8,...,1,6,40,B-3,127.35,145.94,NaN,NaN,209.66,55.25
13,B,3,"[2016-07-19 07:00:00,2016-07-19 07:20:00)",118.43,2016-07-19 07:00:00,999.7,1004.5,239.0,1.9,31.8,...,1,7,0,B-3,97.20,127.35,145.94,NaN,NaN,209.66
14,B,3,"[2016-07-19 07:20:00,2016-07-19 07:40:00)",82.63,2016-07-19 07:20:00,999.7,1004.5,239.0,1.9,31.8,...,1,7,20,B-3,118.43,97.20,127.35,145.94,NaN,NaN
15,B,3,"[2016-07-19 07:40:00,2016-07-19 08:00:00)",110.50,2016-07-19 07:40:00,999.7,1004.5,239.0,1.9,31.8,...,1,7,40,B-3,82.63,118.43,97.20,127.35,145.94,NaN
16,B,3,"[2016-07-19 08:00:00,2016-07-19 08:20:00)",125.76,2016-07-19 08:00:00,999.7,1004.5,239.0,1.9,31.8,...,1,8,0,B-3,110.50,82.63,118.43,97.20,127.35,145.94
17,B,3,"[2016-07-19 08:20:00,2016-07-19 08:40:00)",141.33,2016-07-19 08:20:00,999.7,1004.5,239.0,1.9,31.8,...,1,8,20,B-3,125.76,110.50,82.63,118.43,97.20,127.35
18,B,3,"[2016-07-19 08:40:00,2016-07-19 09:00:00)",176.08,2016-07-19 08:40:00,999.7,1004.5,239.0,1.9,31.8,...,1,8,40,B-3,141.33,125.76,110.50,82.63,118.43,97.20
19,B,3,"[2016-07-19 09:00:00,2016-07-19 09:20:00)",165.29,2016-07-19 09:00:00,998.7,1003.5,218.0,2.0,31.5,...,1,9,0,B-3,176.08,141.33,125.76,110.50,82.63,118.43
20,B,3,"[2016-07-19 09:20:00,2016-07-19 09:40:00)",78.13,2016-07-19 09:20:00,998.7,1003.5,218.0,2.0,31.5,...,1,9,20,B-3,165.29,176.08,141.33,125.76,110.50,82.63
21,B,3,"[2016-07-19 09:40:00,2016-07-19 10:00:00)",117.83,2016-07-19 09:40:00,998.7,1003.5,218.0,2.0,31.5,...,1,9,40,B-3,78.13,165.29,176.08,141.33,125.76,110.50
22,B,3,"[2016-07-19 10:00:00,2016-07-19 10:20:00)",98.92,2016-07-19 10:00:00,998.7,1003.5,218.0,2.0,31.5,...,1,10,0,B-3,117.83,78.13,165.29,176.08,141.33,125.76
23,B,3,"[2016-07-19 10:20:00,2016-07-19 10:40:00)",113.00,2016-07-19 10:20:00,998.7,1003.5,218.0,2.0,31.5,...,1,10,20,B-3,98.92,117.83,78.13,165.29,176.08,141.33
24,B,3,"[2016-07-19 10:40:00,2016-07-19 11:00:00)",98.15,2016-07-19 10:40:00,998.7,1003.5,218.0,2.0,31.5,...,1,10,40,B-3,113.00,98.92,117.83,78.13,165.29,176.08
25,B,3,"[2016-07-19 11:00:00,2016-07-19 11:20:00)",95.98,2016-07-19 11:00:00,998.7,1003.5,218.0,2.0,31.5,...,1,11,0,B-3,98.15,113.00,98.92,117.83,78.13,165.29
26,B,3,"[2016-07-19 11:20:00,2016-07-19 11:40:00)",84.36,2016-07-19 11:20:00,998.7,1003.5,218.0,2.0,31.5,...,1,11,20,B-3,95.98,98.15,113.00,98.92,117.83,78.13
27,B,3,"[2016-07-19 11:40:00,2016-07-19 12:00:00)",96.54,2016-07-19 11:40:00,998.7,1003.5,218.0,2.0,31.5,...,1,11,40,B-3,84.36,95.98,98.15,113.00,98.92,117.83
28,B,3,"[2016-07-19 12:00:00,2016-07-19 12:20:00)",144.87,2016-07-19 12:00:00,1000.2,1005.0,215.0,0.7,30.0,...,1,12,0,B-3,96.54,84.36,95.98,98.15,113.00,98.92
29,B,3,"[2016-07-19 12:20:00,2016-07-19 12:40:00)",136.36,2016-07-19 12:20:00,1000.2,1005.0,215.0,0.7,30.0,...,1,12,20,B-3,144.87,96.54,84.36,95.98,98.15,113.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27282,C,1,"[2016-10-24 10:20:00,2016-10-24 10:40:00)",189.94,2016-10-24 10:20:00,1007.3,1012.3,133.0,0.9,23.5,...,0,10,20,C-1,131.45,149.46,136.74,NaN,157.63,156.72
27283,C,1,"[2016-10-24 10:40:00,2016-10-24 11:00:00)",140.88,2016-10-24 10:40:00,1007.3,1012.3,133.0,0.9,23.5,...,0,10,40,C-1,189.94,131.45,149.46,136.74,NaN,157.63
27284,C,1,"[2016-10-24 11:00:00,2016-10-24 11:20:00)",161.66,2016-10-24 11:00:00,1007.3,1012.3,133.0,0.9,23.5,...,0,11,0,C-1,140.88,189.94,131.45,149.46,136.74,NaN
27285,C,1,"[2016-10-24 11:20:00,2016-10-24 11:40:00)",158.37,2016-10-24 11:20:00,1007.3,1012.3,133.0,0.9,23.5,...,0,11,20,C-1,161.66,140.88,189.94,131.45,149.46,136.74
27286,C,1,"[2016-10-24 11:40:00,2016-10-24 12:00:00)",193.82,2016-10-24 11:40:00,1007.3,1012.3,133.0,0.9,23.5,...,0,11,40,C-1,158.37,161.66,140.88,189.94,131.45,149.46
27287,C,1,"[2016-10-24 12:00:00,2016-10-24 12:20:00)",172.15,2016-10-24 12:00:00,1008.3,1013.3,318.0,2.0,22.4,...,0,12,0,C-1,193.82,158.37,161.66,140.88,189.94,131.45
27288,C,1,"[2016-10-24 12:20:00,2016-10-24 12:40:00)",139.68,2016-10-24 12:20:00,1008.3,1013.3,318.0,2.0,22.4,...,0,12,20,C-1,172.15,193.82,158.37,161.66,140.88,189.94
27289,C,1,"[2016-10-24 12:40:00,2016-10-24 13:00:00)",142.81,2016-10-24 12:40:00,1008.3,1013.3,318.0,2.0,22.4,...,0,12,40,C-1,139.68,172.15,193.82,158.37,161.66,140.88
27290,C,1,"[2016-10-24 13:00:00,2016-10-24 13:20:00)",158.07,2016-10-24 13:00:00,1008.3,1013.3,318.0,2.0,22.4,...,0,13,0,C-1,142.81,139.68,172.15,193.82,158.37,161.66
27291,C,1,"[2016-10-24 13:20:00,2016-10-24 13:40:00)",201.41,2016-10-24 13:20:00,1008.3,1013.3,318.0,2.0,22.4,...,0,13,20,C-1,158.07,142.81,139.68,172.15,193.82,158.37
27292,C,1,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",232.22,2016-10-24 14:00:00,1008.3,1013.3,318.0,2.0,22.4,...,0,14,0,C-1,NaN,201.41,158.07,142.81,139.68,172.15
27293,C,1,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",171.23,2016-10-24 14:40:00,1008.3,1013.3,318.0,2.0,22.4,...,0,14,40,C-1,NaN,232.22,NaN,201.41,158.07,142.81
27294,C,1,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",168.85,2016-10-24 15:00:00,1008.0,1013.0,210.0,1.4,21.0,...,0,15,0,C-1,171.23,NaN,232.22,NaN,201.41,158.07
27295,C,1,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",202.64,2016-10-24 15:20:00,1008.0,1013.0,210.0,1.4,21.0,...,0,15,20,C-1,168.85,171.23,NaN,232.22,NaN,201.41
27296,C,1,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",175.87,2016-10-24 15:40:00,1008.0,1013.0,210.0,1.4,21.0,...,0,15,40,C-1,202.64,168.85,171.23,NaN,232.22,NaN
27297,C,1,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",181.69,2016-10-24 16:00:00,1008.0,1013.0,210.0,1.4,21.0,...,0,16,0,C-1,175.87,202.64,168.85,171.23,NaN,232.22
27298,C,1,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",188.64,2016-10-24 16:20:00,1008.0,1013.0,210.0,1.4,21.0,...,0,16,20,C-1,181.69,175.87,202.64,168.85,171.23,NaN
27299,C,1,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",159.58,2016-10-24 16:40:00,1008.0,1013.0,210.0,1.4,21.0,...,0,16,40,C-1,188.64,181.69,175.87,202.64,168.85,171.23
27300,C,1,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",190.15,2016-10-24 17:00:00,1008.0,1013.0,210.0,1.4,21.0,...,0,17,0,C-1,159.58,188.64,181.69,175.87,202.64,168.85
27301,C,1,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",154.65,2016-10-24 17:20:00,1008.0,1013.0,210.0,1.4,21.0,...,0,17,20,C-1,190.15,159.58,188.64,181.69,175.87,202.64
27302,C,1,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",160.04,2016-10-24 17:40:00,1008.0,1013.0,210.0,1.4,21.0,...,0,17,40,C-1,154.65,190.15,159.58,188.64,181.69,175.87
27303,C,1,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",271.20,2016-10-24 18:00:00,1007.3,1012.3,226.0,3.0,20.7,...,0,18,0,C-1,160.04,154.65,190.15,159.58,188.64,181.69
27304,C,1,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",260.35,2016-10-24 18:20:00,1007.3,1012.3,226.0,3.0,20.7,...,0,18,20,C-1,271.20,160.04,154.65,190.15,159.58,188.64
27305,C,1,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",206.34,2016-10-24 19:00:00,1007.3,1012.3,226.0,3.0,20.7,...,0,19,0,C-1,NaN,260.35,271.20,160.04,154.65,190.15
27306,C,1,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",215.99,2016-10-24 19:20:00,1007.3,1012.3,226.0,3.0,20.7,...,0,19,20,C-1,206.34,NaN,260.35,271.20,160.04,154.65
27307,C,1,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",148.62,2016-10-24 20:00:00,1007.3,1012.3,226.0,3.0,20.7,...,0,20,0,C-1,NaN,215.99,206.34,NaN,260.35,271.20
27308,C,1,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",115.50,2016-10-24 21:00:00,1008.1,1013.1,323.0,2.5,20.8,...,0,21,0,C-1,NaN,NaN,148.62,NaN,215.99,206.34
27309,C,1,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",133.45,2016-10-24 21:20:00,1008.1,1013.1,323.0,2.5,20.8,...,0,21,20,C-1,115.50,NaN,NaN,148.62,NaN,215.99
27310,C,1,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",153.95,2016-10-24 22:20:00,1008.1,1013.1,323.0,2.5,20.8,...,0,22,20,C-1,NaN,NaN,133.45,115.50,NaN,NaN
27311,C,1,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",236.09,2016-10-24 22:40:00,1008.1,1013.1,323.0,2.5,20.8,...,0,22,40,C-1,153.95,NaN,NaN,133.45,115.50,NaN

In [12]:
# 把time映射成1～72
from collections import defaultdict
time_start = datetime(2016,10,17,0,0,0)
timedic = defaultdict(int)
for i in range(72):
    timedic[time_start.time()] = i+1
    time_start = time_start + timedelta(minutes=20)

In [13]:
process_data['timemap'] = process_data['time'].map(lambda x:timedic[x])

In [15]:
process_data['date'][0]

datetime.date(2016, 7, 19)

In [16]:
# 增加法定节假日特征
#holiday = ['2016-09-15','2016-09-16','2016-09-17','2016-10-01','2016-10-02','2016-10-03','2016-10-04','2016-10-05','2016-10-06','2016-10-07']
holiday = [date(2016,9,15),date(2016,9,16),date(2016,9,17),date(2016,10,1),date(2016,10,2),date(2016,10,3),date(2016,10,4),date(2016,10,5),date(2016,10,6),date(2016,10,7)]

def ff(x):
    if x in holiday:
        return 1
    else:
        return 0
process_data['holiday'] = process_data['date'].map(ff)

In [10]:
# 把速度列加上去
#avg_speed = pd.read_csv('avg_speed_all_route_and_last_link.csv')
#process_data['avg_all_route_speed'] = list(avg_speed['avg_all_route_speed'])
#process_data['avg_last_link_speed'] = list(avg_speed['avg_last_link_speed'])

In [14]:
# 写出数据
process_data.to_csv('travel_time_raw_data.csv', index=False)

### 提取流量数据

In [18]:
# 整合流量与天气数据
raw_data2['start_time'] = raw_data2['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:],'%Y-%m-%d %H:%M:%S'))
raw_data2['pair'] = raw_data2['tollgate_id'].astype(str) + '-' + raw_data2['direction'].astype(str)
process_data2 = pd.merge(raw_data2, weather_data, on='start_time', how='left')
# 天气缺失补充
process_data2.fillna(method='ffill', inplace=True)

In [19]:
process_data2 = process_data2.sort_values(by=['tollgate_id', 'direction', 'start_time'])

In [20]:
process_data2

,tollgate_id,time_window,direction,volume,start_time,pair,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation
2,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13,2016-09-19 00:00:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
5,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6,2016-09-19 00:20:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
11,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9,2016-09-19 00:40:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
16,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10,2016-09-19 01:00:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
18,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14,2016-09-19 01:20:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
23,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10,2016-09-19 01:40:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
27,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7,2016-09-19 02:00:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
31,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10,2016-09-19 02:20:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
35,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6,2016-09-19 02:40:00,1-0,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0
40,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9,2016-09-19 03:00:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
42,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4,2016-09-19 03:20:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
48,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9,2016-09-19 03:40:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
50,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10,2016-09-19 04:00:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
56,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13,2016-09-19 04:20:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
58,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12,2016-09-19 04:40:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
65,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2,2016-09-19 05:00:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
69,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8,2016-09-19 05:20:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
75,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13,2016-09-19 05:40:00,1-0,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0
80,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8,2016-09-19 06:00:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
85,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13,2016-09-19 06:20:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
87,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32,2016-09-19 06:40:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
92,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39,2016-09-19 07:00:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
100,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31,2016-09-19 07:20:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
105,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43,2016-09-19 07:40:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
110,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46,2016-09-19 08:00:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
113,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56,2016-09-19 08:20:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
120,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41,2016-09-19 08:40:00,1-0,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0
125,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50,2016-09-19 09:00:00,1-0,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1
130,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49,2016-09-19 09:20:00,1-0,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1
132,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44,2016-09-19 09:40:00,1-0,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12362,3,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",1,102,2016-10-24 14:00:00,3-1,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0
12367,3,"[2016-10-24 14:20:00,2016-10-24 14:40:00)",1,92,2016-10-24 14:20:00,3-1,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0
12369,3,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",1,92,2016-10-24 14:40:00,3-1,1008.3,1013.3,318.0,2.0,22.4,81.0,0.0
12375,3,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",1,80,2016-10-24 15:00:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12379,3,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",1,102,2016-10-24 15:20:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12384,3,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",1,71,2016-10-24 15:40:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12389,3,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",1,101,2016-10-24 16:00:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12394,3,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",1,80,2016-10-24 16:20:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12399,3,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",1,81,2016-10-24 16:40:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12404,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",1,80,2016-10-24 17:00:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12409,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",1,97,2016-10-24 17:20:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12414,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",1,80,2016-10-24 17:40:00,3-1,1008.0,1013.0,210.0,1.4,21.0,91.0,0.0
12419,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",1,91,2016-10-24 18:00:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12425,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",1,94,2016-10-24 18:20:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12429,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",1,74,2016-10-24 18:40:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12437,3,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",1,56,2016-10-24 19:00:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12441,3,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",1,51,2016-10-24 19:20:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12444,3,"[2016-10-24 19:40:00,2016-10-24 20:00:00)",1,58,2016-10-24 19:40:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12451,3,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",1,35,2016-10-24 20:00:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12457,3,"[2016-10-24 20:20:00,2016-10-24 20:40:00)",1,49,2016-10-24 20:20:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12462,3,"[2016-10-24 20:40:00,2016-10-24 21:00:00)",1,43,2016-10-24 20:40:00,3-1,1007.3,1012.3,226.0,3.0,20.7,94.0,0.0
12464,3,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",1,32,2016-10-24 21:00:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12471,3,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",1,38,2016-10-24 21:20:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12475,3,"[2016-10-24 21:40:00,2016-10-24 22:00:00)",1,34,2016-10-24 21:40:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12479,3,"[2016-10-24 22:00:00,2016-10-24 22:20:00)",1,19,2016-10-24 22:00:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12485,3,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",1,30,2016-10-24 22:20:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12490,3,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",1,33,2016-10-24 22:40:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12497,3,"[2016-10-24 23:00:00,2016-10-24 23:20:00)",1,11,2016-10-24 23:00:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12499,3,"[2016-10-24 23:20:00,2016-10-24 23:40:00)",1,13,2016-10-24 23:20:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0
12505,3,"[2016-10-24 23:40:00,2016-10-25 00:00:00)",1,19,2016-10-24 23:40:00,3-1,1008.1,1013.1,323.0,2.5,20.8,93.0,0.0

In [21]:
# 增加星期几和时间窗口两列
process_data2['date'] = process_data2['start_time'].map(lambda x: x.date())
process_data2['weekday'] = process_data2['start_time'].map(lambda x: x.weekday())
process_data2['time'] = process_data2['start_time'].map(lambda x: x.time())
process_data2['hour'] = process_data2['start_time'].map(lambda x: x.hour)
process_data2['minute'] = process_data2['start_time'].map(lambda x: x.minute)

In [22]:
# 增加前20分钟流量特征
start_time = process_data2['start_time']
volume = process_data2['volume']

In [23]:
last_20min = process_data2['volume'].copy() 
last_40min = process_data2['volume'].copy()
last_60min = process_data2['volume'].copy()
last_80min = process_data2['volume'].copy()
last_100min = process_data2['volume'].copy()
last_120min = process_data2['volume'].copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(start_time)):
    cur_time = start_time[i] #当前时间
    # 前20min
    if (i-1) >= 0:
        last20 = cur_time - timedelta(minutes=20)
        if last20 == start_time[i-1]:
            last_20min[i] = volume[i-1]
    # 前40min
    if (i-2) >= 0:
        last40 = cur_time - timedelta(minutes=40)
        for j in range(2):
            if last40 == start_time[i-j-1]:
                last_40min[i] = volume[i-j-1]
                break
    # 前60min
    if (i-3) >= 0:
        last60 = cur_time - timedelta(minutes=60)
        for j in range(3):
            if last60 == start_time[i-j-1]:
                last_60min[i] = volume[i-j-1]
                break
    # 前80min
    if (i-4) >= 0:
        last80 = cur_time - timedelta(minutes=80)
        for j in range(4):
            if last80 == start_time[i-j-1]:
                last_80min[i] = volume[i-j-1]
                break
    # 前100min
    if (i-5) >= 0:
        last100 = cur_time - timedelta(minutes=100)
        for j in range(5):
            if last100 == start_time[i-j-1]:
                last_100min[i] = volume[i-j-1]
                break
    # 前120min
    if (i-6) >= 0:
        last120 = cur_time - timedelta(minutes=120)
        for j in range(6):
            if last120 == start_time[i-j-1]:
                last_120min[i] = volume[i-j-1]
                break

process_data2['last_20min'] = last_20min
process_data2['last_40min'] = last_40min
process_data2['last_60min'] = last_60min
process_data2['last_80min'] = last_80min
process_data2['last_100min'] = last_100min
process_data2['last_120min'] = last_120min

In [24]:
process_data2

,tollgate_id,time_window,direction,volume,start_time,pair,pressure,sea_pressure,wind_direction,wind_speed,...,weekday,time,hour,minute,last_20min,last_40min,last_60min,last_80min,last_100min,last_120min
2,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13,2016-09-19 00:00:00,1-0,1008.2,1013.2,329.0,2.8,...,0,00:00:00,0,0,NaN,NaN,NaN,NaN,NaN,NaN
5,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6,2016-09-19 00:20:00,1-0,1008.2,1013.2,329.0,2.8,...,0,00:20:00,0,20,2.0,NaN,NaN,NaN,NaN,NaN
11,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9,2016-09-19 00:40:00,1-0,1008.2,1013.2,329.0,2.8,...,0,00:40:00,0,40,NaN,NaN,NaN,NaN,NaN,NaN
16,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10,2016-09-19 01:00:00,1-0,1008.2,1013.2,329.0,2.8,...,0,01:00:00,1,0,NaN,NaN,NaN,NaN,NaN,NaN
18,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14,2016-09-19 01:20:00,1-0,1008.2,1013.2,329.0,2.8,...,0,01:20:00,1,20,4.0,NaN,NaN,NaN,NaN,NaN
23,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10,2016-09-19 01:40:00,1-0,1008.2,1013.2,329.0,2.8,...,0,01:40:00,1,40,NaN,NaN,NaN,NaN,NaN,NaN
27,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7,2016-09-19 02:00:00,1-0,1008.2,1013.2,329.0,2.8,...,0,02:00:00,2,0,4.0,NaN,NaN,NaN,NaN,NaN
31,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10,2016-09-19 02:20:00,1-0,1008.2,1013.2,329.0,2.8,...,0,02:20:00,2,20,5.0,NaN,NaN,NaN,NaN,NaN
35,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6,2016-09-19 02:40:00,1-0,1008.2,1013.2,329.0,2.8,...,0,02:40:00,2,40,4.0,NaN,NaN,NaN,NaN,NaN
40,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9,2016-09-19 03:00:00,1-0,1008.3,1013.3,15.0,4.5,...,0,03:00:00,3,0,NaN,NaN,NaN,NaN,NaN,NaN
42,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4,2016-09-19 03:20:00,1-0,1008.3,1013.3,15.0,4.5,...,0,03:20:00,3,20,10.0,NaN,NaN,NaN,NaN,NaN
48,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9,2016-09-19 03:40:00,1-0,1008.3,1013.3,15.0,4.5,...,0,03:40:00,3,40,NaN,NaN,NaN,NaN,NaN,NaN
50,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10,2016-09-19 04:00:00,1-0,1008.3,1013.3,15.0,4.5,...,0,04:00:00,4,0,20.0,NaN,NaN,NaN,NaN,NaN
56,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13,2016-09-19 04:20:00,1-0,1008.3,1013.3,15.0,4.5,...,0,04:20:00,4,20,NaN,NaN,NaN,NaN,NaN,NaN
58,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12,2016-09-19 04:40:00,1-0,1008.3,1013.3,15.0,4.5,...,0,04:40:00,4,40,17.0,NaN,NaN,NaN,NaN,NaN
65,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2,2016-09-19 05:00:00,1-0,1008.3,1013.3,15.0,4.5,...,0,05:00:00,5,0,NaN,NaN,NaN,NaN,NaN,NaN
69,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8,2016-09-19 05:20:00,1-0,1008.3,1013.3,15.0,4.5,...,0,05:20:00,5,20,NaN,NaN,NaN,NaN,NaN,NaN
75,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13,2016-09-19 05:40:00,1-0,1008.3,1013.3,15.0,4.5,...,0,05:40:00,5,40,NaN,NaN,NaN,NaN,NaN,NaN
80,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8,2016-09-19 06:00:00,1-0,1007.4,1012.3,12.0,6.2,...,0,06:00:00,6,0,NaN,NaN,NaN,NaN,NaN,NaN
85,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13,2016-09-19 06:20:00,1-0,1007.4,1012.3,12.0,6.2,...,0,06:20:00,6,20,NaN,NaN,NaN,NaN,NaN,NaN
87,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32,2016-09-19 06:40:00,1-0,1007.4,1012.3,12.0,6.2,...,0,06:40:00,6,40,57.0,NaN,NaN,NaN,NaN,NaN
92,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39,2016-09-19 07:00:00,1-0,1007.4,1012.3,12.0,6.2,...,0,07:00:00,7,0,65.0,NaN,NaN,NaN,NaN,NaN
100,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31,2016-09-19 07:20:00,1-0,1007.4,1012.3,12.0,6.2,...,0,07:20:00,7,20,NaN,NaN,NaN,NaN,NaN,NaN
105,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43,2016-09-19 07:40:00,1-0,1007.4,1012.3,12.0,6.2,...,0,07:40:00,7,40,NaN,NaN,NaN,NaN,NaN,NaN
110,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46,2016-09-19 08:00:00,1-0,1007.4,1012.3,12.0,6.2,...,0,08:00:00,8,0,NaN,NaN,NaN,NaN,NaN,NaN
113,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56,2016-09-19 08:20:00,1-0,1007.4,1012.3,12.0,6.2,...,0,08:20:00,8,20,NaN,NaN,NaN,NaN,NaN,NaN
120,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41,2016-09-19 08:40:00,1-0,1007.4,1012.3,12.0,6.2,...,0,08:40:00,8,40,NaN,NaN,NaN,NaN,NaN,NaN
125,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50,2016-09-19 09:00:00,1-0,1008.3,1013.3,351.0,5.3,...,0,09:00:00,9,0,NaN,NaN,NaN,NaN,NaN,NaN
130,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49,2016-09-19 09:20:00,1-0,1008.3,1013.3,351.0,5.3,...,0,09:20:00,9,20,NaN,NaN,NaN,NaN,NaN,NaN
132,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44,2016-09-19 09:40:00,1-0,1008.3,1013.3,351.0,5.3,...,0,09:40:00,9,40,151.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12362,3,"[2016-10-24 14:00:00,2016-10-24 14:20:00)",1,102,2016-10-24 14:00:00,3-1,1008.3,1013.3,318.0,2.0,...,0,14:00:00,14,0,NaN,NaN,NaN,NaN,NaN,NaN
12367,3,"[2016-10-24 14:20:00,2016-10-24 14:40:00)",1,92,2016-10-24 14:20:00,3-1,1008.3,1013.3,318.0,2.0,...,0,14:20:00,14,20,NaN,NaN,NaN,NaN,NaN,NaN
12369,3,"[2016-10-24 14:40:00,2016-10-24 15:00:00)",1,92,2016-10-24 14:40:00,3-1,1008.3,1013.3,318.0,2.0,...,0,14:40:00,14,40,NaN,NaN,NaN,NaN,NaN,NaN
12375,3,"[2016-10-24 15:00:00,2016-10-24 15:20:00)",1,80,2016-10-24 15:00:00,3-1,1008.0,1013.0,210.0,1.4,...,0,15:00:00,15,0,NaN,NaN,NaN,NaN,NaN,NaN
12379,3,"[2016-10-24 15:20:00,2016-10-24 15:40:00)",1,102,2016-10-24 15:20:00,3-1,1008.0,1013.0,210.0,1.4,...,0,15:20:00,15,20,NaN,NaN,NaN,NaN,NaN,NaN
12384,3,"[2016-10-24 15:40:00,2016-10-24 16:00:00)",1,71,2016-10-24 15:40:00,3-1,1008.0,1013.0,210.0,1.4,...,0,15:40:00,15,40,NaN,NaN,NaN,NaN,NaN,NaN
12389,3,"[2016-10-24 16:00:00,2016-10-24 16:20:00)",1,101,2016-10-24 16:00:00,3-1,1008.0,1013.0,210.0,1.4,...,0,16:00:00,16,0,NaN,NaN,NaN,NaN,NaN,NaN
12394,3,"[2016-10-24 16:20:00,2016-10-24 16:40:00)",1,80,2016-10-24 16:20:00,3-1,1008.0,1013.0,210.0,1.4,...,0,16:20:00,16,20,NaN,NaN,NaN,NaN,NaN,NaN
12399,3,"[2016-10-24 16:40:00,2016-10-24 17:00:00)",1,81,2016-10-24 16:40:00,3-1,1008.0,1013.0,210.0,1.4,...,0,16:40:00,16,40,NaN,NaN,NaN,NaN,NaN,NaN
12404,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",1,80,2016-10-24 17:00:00,3-1,1008.0,1013.0,210.0,1.4,...,0,17:00:00,17,0,NaN,NaN,NaN,NaN,NaN,NaN
12409,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",1,97,2016-10-24 17:20:00,3-1,1008.0,1013.0,210.0,1.4,...,0,17:20:00,17,20,NaN,NaN,NaN,NaN,NaN,NaN
12414,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",1,80,2016-10-24 17:40:00,3-1,1008.0,1013.0,210.0,1.4,...,0,17:40:00,17,40,NaN,NaN,NaN,NaN,NaN,NaN
12419,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",1,91,2016-10-24 18:00:00,3-1,1007.3,1012.3,226.0,3.0,...,0,18:00:00,18,0,NaN,NaN,NaN,NaN,NaN,NaN
12425,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",1,94,2016-10-24 18:20:00,3-1,1007.3,1012.3,226.0,3.0,...,0,18:20:00,18,20,NaN,NaN,NaN,NaN,NaN,NaN
12429,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",1,74,2016-10-24 18:40:00,3-1,1007.3,1012.3,226.0,3.0,...,0,18:40:00,18,40,NaN,NaN,NaN,NaN,NaN,NaN
12437,3,"[2016-10-24 19:00:00,2016-10-24 19:20:00)",1,56,2016-10-24 19:00:00,3-1,1007.3,1012.3,226.0,3.0,...,0,19:00:00,19,0,NaN,NaN,NaN,NaN,NaN,NaN
12441,3,"[2016-10-24 19:20:00,2016-10-24 19:40:00)",1,51,2016-10-24 19:20:00,3-1,1007.3,1012.3,226.0,3.0,...,0,19:20:00,19,20,NaN,NaN,NaN,NaN,NaN,NaN
12444,3,"[2016-10-24 19:40:00,2016-10-24 20:00:00)",1,58,2016-10-24 19:40:00,3-1,1007.3,1012.3,226.0,3.0,...,0,19:40:00,19,40,NaN,NaN,NaN,NaN,NaN,NaN
12451,3,"[2016-10-24 20:00:00,2016-10-24 20:20:00)",1,35,2016-10-24 20:00:00,3-1,1007.3,1012.3,226.0,3.0,...,0,20:00:00,20,0,NaN,NaN,NaN,NaN,NaN,NaN
12457,3,"[2016-10-24 20:20:00,2016-10-24 20:40:00)",1,49,2016-10-24 20:20:00,3-1,1007.3,1012.3,226.0,3.0,...,0,20:20:00,20,20,NaN,NaN,NaN,NaN,NaN,NaN
12462,3,"[2016-10-24 20:40:00,2016-10-24 21:00:00)",1,43,2016-10-24 20:40:00,3-1,1007.3,1012.3,226.0,3.0,...,0,20:40:00,20,40,NaN,NaN,NaN,NaN,NaN,NaN
12464,3,"[2016-10-24 21:00:00,2016-10-24 21:20:00)",1,32,2016-10-24 21:00:00,3-1,1008.1,1013.1,323.0,2.5,...,0,21:00:00,21,0,NaN,NaN,NaN,NaN,NaN,NaN
12471,3,"[2016-10-24 21:20:00,2016-10-24 21:40:00)",1,38,2016-10-24 21:20:00,3-1,1008.1,1013.1,323.0,2.5,...,0,21:20:00,21,20,NaN,NaN,NaN,NaN,NaN,NaN
12475,3,"[2016-10-24 21:40:00,2016-10-24 22:00:00)",1,34,2016-10-24 21:40:00,3-1,1008.1,1013.1,323.0,2.5,...,0,21:40:00,21,40,NaN,NaN,NaN,NaN,NaN,NaN
12479,3,"[2016-10-24 22:00:00,2016-10-24 22:20:00)",1,19,2016-10-24 22:00:00,3-1,1008.1,1013.1,323.0,2.5,...,0,22:00:00,22,0,NaN,NaN,NaN,NaN,NaN,NaN
12485,3,"[2016-10-24 22:20:00,2016-10-24 22:40:00)",1,30,2016-10-24 22:20:00,3-1,1008.1,1013.1,323.0,2.5,...,0,22:20:00,22,20,NaN,NaN,NaN,NaN,NaN,NaN
12490,3,"[2016-10-24 22:40:00,2016-10-24 23:00:00)",1,33,2016-10-24 22:40:00,3-1,1008.1,1013.1,323.0,2.5,...,0,22:40:00,22,40,NaN,NaN,NaN,NaN,NaN,NaN
12497,3,"[2016-10-24 23:00:00,2016-10-24 23:20:00)",1,11,2016-10-24 23:00:00,3-1,1008.1,1013.1,323.0,2.5,...,0,23:00:00,23,0,NaN,NaN,NaN,NaN,NaN,NaN
12499,3,"[2016-10-24 23:20:00,2016-10-24 23:40:00)",1,13,2016-10-24 23:20:00,3-1,1008.1,1013.1,323.0,2.5,...,0,23:20:00,23,20,NaN,NaN,NaN,NaN,NaN,NaN
12505,3,"[2016-10-24 23:40:00,2016-10-25 00:00:00)",1,19,2016-10-24 23:40:00,3-1,1008.1,1013.1,323.0,2.5,...,0,23:40:00,23,40,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# 时间映射成1～72
process_data2['timemap'] = process_data2['time'].map(lambda x:timedic[x])

In [26]:
process_data2['date'][0]

datetime.date(2016, 9, 19)

In [16]:
process_data2['holiday'] = process_data2['date'].map(ff)

In [17]:
# 写出数据
process_data2.to_csv('volume_raw_data_ffill.csv', index=False)

### 测试集