# KDDCUP TestData Extract

2017-05-12

### 录入数据

In [28]:
import numpy as np
import pandas as pd
from datetime import datetime,timedelta,date,time
import copy

In [29]:
# 读入平均时间，流量和天气数据（平均时间和流量由aggregate_travel_time.py和aggregate_volume.py生成）
test_travel_time_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/test_20min_avg_travel_time.csv'
test_volume_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/时间窗数据/test_20min_avg_volume.csv'
test_weather_infile = '/home/godcedric/GitLocal/KDDCUP2017/final_data/原始数据/weather_test.csv'
test1 = pd.read_csv(test_travel_time_infile)
test2 = pd.read_csv(test_volume_infile)
weather_data = pd.read_csv(test_weather_infile)

In [30]:
# 测试特征集
test_travel_time = pd.read_csv('/home/godcedric/GitLocal/KDDCUP2017/final_data/原始数据/submission_sample_travelTime.csv')
test_volume = pd.read_csv('/home/godcedric/GitLocal/KDDCUP2017/final_data/原始数据/submission_sample_volume.csv')

### 生成平均时间测试特征集

In [31]:
del test_travel_time['avg_travel_time']
test_travel_time['start_time'] = test_travel_time['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:], '%Y-%m-%d %H:%M:%S'))

In [32]:
# 天气特征
weather_data['hour'] = weather_data['hour'].map(lambda x: ' ' + time(x, 0, 0).strftime('%H:%M:%S'))
weather_data['start_time'] = weather_data['date'] + weather_data['hour']
weather_data['start_time'] = weather_data['start_time'].map(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
num = len(weather_data)
for i in range(num):
    temp = weather_data.ix[i]
    temp1 = copy.deepcopy(temp)
    temp2 = copy.deepcopy(temp)
    temp3 = copy.deepcopy(temp)
    temp4 = copy.deepcopy(temp)
    temp5 = copy.deepcopy(temp)
    temp6 = copy.deepcopy(temp)
    temp7 = copy.deepcopy(temp)
    temp8 = copy.deepcopy(temp)
    stime = temp.start_time
    temp1.start_time = stime + timedelta(minutes=20)
    temp2.start_time = stime + timedelta(minutes=40)
    temp3.start_time = stime + timedelta(minutes=60)
    temp4.start_time = stime + timedelta(minutes=80)
    temp5.start_time = stime + timedelta(minutes=100)
    temp6.start_time = stime + timedelta(minutes=120)
    temp7.start_time = stime + timedelta(minutes=140)
    temp8.start_time = stime + timedelta(minutes=160)
    alltemp = [temp1, temp2, temp3, temp4, temp5, temp6, temp7, temp8]
    alltemp = pd.DataFrame(alltemp)
    weather_data = pd.concat([weather_data, alltemp])

In [33]:
test_travel_time = pd.merge(test_travel_time, weather_data, on='start_time', how='left')
del test_travel_time['hour']
test_travel_time['time'] = test_travel_time['start_time'].map(lambda x: x.time())

In [34]:
# weekday特征
test_travel_time['weekday'] = test_travel_time['start_time'].map(lambda x: x.weekday())

In [35]:
# route特征
test_travel_time['route'] = test_travel_time['intersection_id'].astype(str) + '-' + test_travel_time['tollgate_id'].astype(str)

In [36]:
# last_20min特征
test1['start_time'] = test1['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:], '%Y-%m-%d %H:%M:%S') + timedelta(hours=2))
del test1['time_window']
test_for_last20min = pd.merge(test_travel_time, test1, on=['intersection_id','tollgate_id','start_time'], how='left')

In [37]:
test_for_last20min

,intersection_id,tollgate_id,time_window,start_time,date,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,time,weekday,route,avg_travel_time
0,A,2,"[2016-10-25 08:00:00,2016-10-25 08:20:00)",2016-10-25 08:00:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:00:00,1,A-2,29.74
1,A,2,"[2016-10-25 08:20:00,2016-10-25 08:40:00)",2016-10-25 08:20:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:20:00,1,A-2,56.42
2,A,2,"[2016-10-25 08:40:00,2016-10-25 09:00:00)",2016-10-25 08:40:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:40:00,1,A-2,47.73
3,A,2,"[2016-10-25 09:00:00,2016-10-25 09:20:00)",2016-10-25 09:00:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:00:00,1,A-2,43.19
4,A,2,"[2016-10-25 09:20:00,2016-10-25 09:40:00)",2016-10-25 09:20:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:20:00,1,A-2,69.81
5,A,2,"[2016-10-25 09:40:00,2016-10-25 10:00:00)",2016-10-25 09:40:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:40:00,1,A-2,60.60
6,A,2,"[2016-10-26 08:00:00,2016-10-26 08:20:00)",2016-10-26 08:00:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:00:00,2,A-2,56.70
7,A,2,"[2016-10-26 08:20:00,2016-10-26 08:40:00)",2016-10-26 08:20:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:20:00,2,A-2,59.10
8,A,2,"[2016-10-26 08:40:00,2016-10-26 09:00:00)",2016-10-26 08:40:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:40:00,2,A-2,72.18
9,A,2,"[2016-10-26 09:00:00,2016-10-26 09:20:00)",2016-10-26 09:00:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:00:00,2,A-2,63.80
10,A,2,"[2016-10-26 09:20:00,2016-10-26 09:40:00)",2016-10-26 09:20:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:20:00,2,A-2,101.67
11,A,2,"[2016-10-26 09:40:00,2016-10-26 10:00:00)",2016-10-26 09:40:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:40:00,2,A-2,46.54
12,A,2,"[2016-10-27 08:00:00,2016-10-27 08:20:00)",2016-10-27 08:00:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:00:00,3,A-2,43.50
13,A,2,"[2016-10-27 08:20:00,2016-10-27 08:40:00)",2016-10-27 08:20:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:20:00,3,A-2,39.25
14,A,2,"[2016-10-27 08:40:00,2016-10-27 09:00:00)",2016-10-27 08:40:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:40:00,3,A-2,89.51
15,A,2,"[2016-10-27 09:00:00,2016-10-27 09:20:00)",2016-10-27 09:00:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:00:00,3,A-2,55.22
16,A,2,"[2016-10-27 09:20:00,2016-10-27 09:40:00)",2016-10-27 09:20:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:20:00,3,A-2,57.70
17,A,2,"[2016-10-27 09:40:00,2016-10-27 10:00:00)",2016-10-27 09:40:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:40:00,3,A-2,80.52
18,A,2,"[2016-10-28 08:00:00,2016-10-28 08:20:00)",2016-10-28 08:00:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:00:00,4,A-2,50.19
19,A,2,"[2016-10-28 08:20:00,2016-10-28 08:40:00)",2016-10-28 08:20:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:20:00,4,A-2,52.57
20,A,2,"[2016-10-28 08:40:00,2016-10-28 09:00:00)",2016-10-28 08:40:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:40:00,4,A-2,58.58
21,A,2,"[2016-10-28 09:00:00,2016-10-28 09:20:00)",2016-10-28 09:00:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:00:00,4,A-2,62.71
22,A,2,"[2016-10-28 09:20:00,2016-10-28 09:40:00)",2016-10-28 09:20:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:20:00,4,A-2,53.71
23,A,2,"[2016-10-28 09:40:00,2016-10-28 10:00:00)",2016-10-28 09:40:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:40:00,4,A-2,65.17
24,A,2,"[2016-10-29 08:00:00,2016-10-29 08:20:00)",2016-10-29 08:00:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:00:00,5,A-2,52.40
25,A,2,"[2016-10-29 08:20:00,2016-10-29 08:40:00)",2016-10-29 08:20:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:20:00,5,A-2,42.98
26,A,2,"[2016-10-29 08:40:00,2016-10-29 09:00:00)",2016-10-29 08:40:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:40:00,5,A-2,53.96
27,A,2,"[2016-10-29 09:00:00,2016-10-29 09:20:00)",2016-10-29 09:00:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:00:00,5,A-2,51.20
28,A,2,"[2016-10-29 09:20:00,2016-10-29 09:40:00)",2016-10-29 09:20:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:20:00,5,A-2,65.35
29,A,2,"[2016-10-29 09:40:00,2016-10-29 10:00:00)",2016-10-29 09:40:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:40:00,5,A-2,53.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,C,3,"[2016-10-27 17:00:00,2016-10-27 17:20:00)",2016-10-27 17:00:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:00:00,3,C-3,NaN
475,C,3,"[2016-10-27 17:20:00,2016-10-27 17:40:00)",2016-10-27 17:20:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:20:00,3,C-3,NaN
476,C,3,"[2016-10-27 17:40:00,2016-10-27 18:00:00)",2016-10-27 17:40:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:40:00,3,C-3,NaN
477,C,3,"[2016-10-27 18:00:00,2016-10-27 18:20:00)",2016-10-27 18:00:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:00:00,3,C-3,270.26
478,C,3,"[2016-10-27 18:20:00,2016-10-27 18:40:00)",2016-10-27 18:20:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:20:00,3,C-3,124.10
479,C,3,"[2016-10-27 18:40:00,2016-10-27 19:00:00)",2016-10-27 18:40:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:40:00,3,C-3,158.78
480,C,3,"[2016-10-28 17:00:00,2016-10-28 17:20:00)",2016-10-28 17:00:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:00:00,4,C-3,147.37
481,C,3,"[2016-10-28 17:20:00,2016-10-28 17:40:00)",2016-10-28 17:20:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:20:00,4,C-3,238.11
482,C,3,"[2016-10-28 17:40:00,2016-10-28 18:00:00)",2016-10-28 17:40:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:40:00,4,C-3,140.45
483,C,3,"[2016-10-28 18:00:00,2016-10-28 18:20:00)",2016-10-28 18:00:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:00:00,4,C-3,183.93
484,C,3,"[2016-10-28 18:20:00,2016-10-28 18:40:00)",2016-10-28 18:20:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:20:00,4,C-3,149.50
485,C,3,"[2016-10-28 18:40:00,2016-10-28 19:00:00)",2016-10-28 18:40:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:40:00,4,C-3,138.78
486,C,3,"[2016-10-29 17:00:00,2016-10-29 17:20:00)",2016-10-29 17:00:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:00:00,5,C-3,170.41
487,C,3,"[2016-10-29 17:20:00,2016-10-29 17:40:00)",2016-10-29 17:20:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:20:00,5,C-3,NaN
488,C,3,"[2016-10-29 17:40:00,2016-10-29 18:00:00)",2016-10-29 17:40:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:40:00,5,C-3,199.81
489,C,3,"[2016-10-29 18:00:00,2016-10-29 18:20:00)",2016-10-29 18:00:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:00:00,5,C-3,163.95
490,C,3,"[2016-10-29 18:20:00,2016-10-29 18:40:00)",2016-10-29 18:20:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:20:00,5,C-3,228.04
491,C,3,"[2016-10-29 18:40:00,2016-10-29 19:00:00)",2016-10-29 18:40:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:40:00,5,C-3,NaN
492,C,3,"[2016-10-30 17:00:00,2016-10-30 17:20:00)",2016-10-30 17:00:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:00:00,6,C-3,232.71
493,C,3,"[2016-10-30 17:20:00,2016-10-30 17:40:00)",2016-10-30 17:20:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:20:00,6,C-3,218.07
494,C,3,"[2016-10-30 17:40:00,2016-10-30 18:00:00)",2016-10-30 17:40:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:40:00,6,C-3,225.89
495,C,3,"[2016-10-30 18:00:00,2016-10-30 18:20:00)",2016-10-30 18:00:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:00:00,6,C-3,226.33
496,C,3,"[2016-10-30 18:20:00,2016-10-30 18:40:00)",2016-10-30 18:20:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:20:00,6,C-3,159.06
497,C,3,"[2016-10-30 18:40:00,2016-10-30 19:00:00)",2016-10-30 18:40:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:40:00,6,C-3,215.88
498,C,3,"[2016-10-31 17:00:00,2016-10-31 17:20:00)",2016-10-31 17:00:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:00:00,0,C-3,108.04
499,C,3,"[2016-10-31 17:20:00,2016-10-31 17:40:00)",2016-10-31 17:20:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:20:00,0,C-3,158.86
500,C,3,"[2016-10-31 17:40:00,2016-10-31 18:00:00)",2016-10-31 17:40:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:40:00,0,C-3,215.31
501,C,3,"[2016-10-31 18:00:00,2016-10-31 18:20:00)",2016-10-31 18:00:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:00:00,0,C-3,192.58
502,C,3,"[2016-10-31 18:20:00,2016-10-31 18:40:00)",2016-10-31 18:20:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:20:00,0,C-3,158.13
503,C,3,"[2016-10-31 18:40:00,2016-10-31 19:00:00)",2016-10-31 18:40:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:40:00,0,C-3,177.77

In [15]:
# 以均值填充缺失值
fill_mean = lambda g:g.fillna(g.mean())

test_for_last20min['avg_travel_time'] = test_for_last20min.groupby(['route','time'])['avg_travel_time'].apply(fill_mean)

In [38]:
# 以最近值填充缺失值
ffill = lambda g:g.fillna(method='ffill')
bfill = lambda g:g.fillna(method='bfill')

test_for_last20min = test_for_last20min.groupby(['route','time']).apply(ffill)
test_for_last20min = test_for_last20min.groupby(['route','time']).apply(bfill)

In [39]:
test_for_last20min

,intersection_id,tollgate_id,time_window,start_time,date,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,time,weekday,route,avg_travel_time
0,A,2,"[2016-10-25 08:00:00,2016-10-25 08:20:00)",2016-10-25 08:00:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:00:00,1,A-2,29.74
1,A,2,"[2016-10-25 08:20:00,2016-10-25 08:40:00)",2016-10-25 08:20:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:20:00,1,A-2,56.42
2,A,2,"[2016-10-25 08:40:00,2016-10-25 09:00:00)",2016-10-25 08:40:00,2016-10-25,1010.2,1015.2,37.0,4.3,19.5,78.0,0.0,08:40:00,1,A-2,47.73
3,A,2,"[2016-10-25 09:00:00,2016-10-25 09:20:00)",2016-10-25 09:00:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:00:00,1,A-2,43.19
4,A,2,"[2016-10-25 09:20:00,2016-10-25 09:40:00)",2016-10-25 09:20:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:20:00,1,A-2,69.81
5,A,2,"[2016-10-25 09:40:00,2016-10-25 10:00:00)",2016-10-25 09:40:00,2016-10-25,1011.3,1016.3,7.0,3.8,18.0,81.0,0.0,09:40:00,1,A-2,60.60
6,A,2,"[2016-10-26 08:00:00,2016-10-26 08:20:00)",2016-10-26 08:00:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:00:00,2,A-2,56.70
7,A,2,"[2016-10-26 08:20:00,2016-10-26 08:40:00)",2016-10-26 08:20:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:20:00,2,A-2,59.10
8,A,2,"[2016-10-26 08:40:00,2016-10-26 09:00:00)",2016-10-26 08:40:00,2016-10-26,1007.7,1012.7,216.0,2.1,28.1,67.0,0.0,08:40:00,2,A-2,72.18
9,A,2,"[2016-10-26 09:00:00,2016-10-26 09:20:00)",2016-10-26 09:00:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:00:00,2,A-2,63.80
10,A,2,"[2016-10-26 09:20:00,2016-10-26 09:40:00)",2016-10-26 09:20:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:20:00,2,A-2,101.67
11,A,2,"[2016-10-26 09:40:00,2016-10-26 10:00:00)",2016-10-26 09:40:00,2016-10-26,1010.2,1015.2,356.0,5.6,21.6,81.0,0.0,09:40:00,2,A-2,46.54
12,A,2,"[2016-10-27 08:00:00,2016-10-27 08:20:00)",2016-10-27 08:00:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:00:00,3,A-2,43.50
13,A,2,"[2016-10-27 08:20:00,2016-10-27 08:40:00)",2016-10-27 08:20:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:20:00,3,A-2,39.25
14,A,2,"[2016-10-27 08:40:00,2016-10-27 09:00:00)",2016-10-27 08:40:00,2016-10-27,1010.8,1015.8,339.0,1.8,19.7,93.0,0.0,08:40:00,3,A-2,89.51
15,A,2,"[2016-10-27 09:00:00,2016-10-27 09:20:00)",2016-10-27 09:00:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:00:00,3,A-2,55.22
16,A,2,"[2016-10-27 09:20:00,2016-10-27 09:40:00)",2016-10-27 09:20:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:20:00,3,A-2,57.70
17,A,2,"[2016-10-27 09:40:00,2016-10-27 10:00:00)",2016-10-27 09:40:00,2016-10-27,1010.4,1015.4,107.0,0.5,20.7,90.0,0.0,09:40:00,3,A-2,80.52
18,A,2,"[2016-10-28 08:00:00,2016-10-28 08:20:00)",2016-10-28 08:00:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:00:00,4,A-2,50.19
19,A,2,"[2016-10-28 08:20:00,2016-10-28 08:40:00)",2016-10-28 08:20:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:20:00,4,A-2,52.57
20,A,2,"[2016-10-28 08:40:00,2016-10-28 09:00:00)",2016-10-28 08:40:00,2016-10-28,1016.6,1021.7,4.0,6.0,16.2,91.0,0.1,08:40:00,4,A-2,58.58
21,A,2,"[2016-10-28 09:00:00,2016-10-28 09:20:00)",2016-10-28 09:00:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:00:00,4,A-2,62.71
22,A,2,"[2016-10-28 09:20:00,2016-10-28 09:40:00)",2016-10-28 09:20:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:20:00,4,A-2,53.71
23,A,2,"[2016-10-28 09:40:00,2016-10-28 10:00:00)",2016-10-28 09:40:00,2016-10-28,1018.8,1023.9,1.0,5.9,15.1,86.0,0.0,09:40:00,4,A-2,65.17
24,A,2,"[2016-10-29 08:00:00,2016-10-29 08:20:00)",2016-10-29 08:00:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:00:00,5,A-2,52.40
25,A,2,"[2016-10-29 08:20:00,2016-10-29 08:40:00)",2016-10-29 08:20:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:20:00,5,A-2,42.98
26,A,2,"[2016-10-29 08:40:00,2016-10-29 09:00:00)",2016-10-29 08:40:00,2016-10-29,1024.0,1029.2,36.0,3.2,14.6,71.0,0.0,08:40:00,5,A-2,53.96
27,A,2,"[2016-10-29 09:00:00,2016-10-29 09:20:00)",2016-10-29 09:00:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:00:00,5,A-2,51.20
28,A,2,"[2016-10-29 09:20:00,2016-10-29 09:40:00)",2016-10-29 09:20:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:20:00,5,A-2,65.35
29,A,2,"[2016-10-29 09:40:00,2016-10-29 10:00:00)",2016-10-29 09:40:00,2016-10-29,1024.6,1029.8,8.0,3.4,13.6,76.0,0.0,09:40:00,5,A-2,53.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,C,3,"[2016-10-27 17:00:00,2016-10-27 17:20:00)",2016-10-27 17:00:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:00:00,3,C-3,244.31
475,C,3,"[2016-10-27 17:20:00,2016-10-27 17:40:00)",2016-10-27 17:20:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:20:00,3,C-3,141.96
476,C,3,"[2016-10-27 17:40:00,2016-10-27 18:00:00)",2016-10-27 17:40:00,2016-10-27,1010.3,1015.3,238.0,1.9,19.8,95.0,0.0,17:40:00,3,C-3,182.12
477,C,3,"[2016-10-27 18:00:00,2016-10-27 18:20:00)",2016-10-27 18:00:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:00:00,3,C-3,270.26
478,C,3,"[2016-10-27 18:20:00,2016-10-27 18:40:00)",2016-10-27 18:20:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:20:00,3,C-3,124.10
479,C,3,"[2016-10-27 18:40:00,2016-10-27 19:00:00)",2016-10-27 18:40:00,2016-10-27,1009.8,1014.8,357.0,2.5,19.5,97.0,0.0,18:40:00,3,C-3,158.78
480,C,3,"[2016-10-28 17:00:00,2016-10-28 17:20:00)",2016-10-28 17:00:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:00:00,4,C-3,147.37
481,C,3,"[2016-10-28 17:20:00,2016-10-28 17:40:00)",2016-10-28 17:20:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:20:00,4,C-3,238.11
482,C,3,"[2016-10-28 17:40:00,2016-10-28 18:00:00)",2016-10-28 17:40:00,2016-10-28,1022.0,1027.1,345.0,4.7,13.9,95.0,0.3,17:40:00,4,C-3,140.45
483,C,3,"[2016-10-28 18:00:00,2016-10-28 18:20:00)",2016-10-28 18:00:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:00:00,4,C-3,183.93
484,C,3,"[2016-10-28 18:20:00,2016-10-28 18:40:00)",2016-10-28 18:20:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:20:00,4,C-3,149.50
485,C,3,"[2016-10-28 18:40:00,2016-10-28 19:00:00)",2016-10-28 18:40:00,2016-10-28,1021.1,1026.3,355.0,3.4,13.9,95.0,0.2,18:40:00,4,C-3,138.78
486,C,3,"[2016-10-29 17:00:00,2016-10-29 17:20:00)",2016-10-29 17:00:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:00:00,5,C-3,170.41
487,C,3,"[2016-10-29 17:20:00,2016-10-29 17:40:00)",2016-10-29 17:20:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:20:00,5,C-3,238.11
488,C,3,"[2016-10-29 17:40:00,2016-10-29 18:00:00)",2016-10-29 17:40:00,2016-10-29,1026.4,1031.6,339.0,1.6,12.9,84.0,0.0,17:40:00,5,C-3,199.81
489,C,3,"[2016-10-29 18:00:00,2016-10-29 18:20:00)",2016-10-29 18:00:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:00:00,5,C-3,163.95
490,C,3,"[2016-10-29 18:20:00,2016-10-29 18:40:00)",2016-10-29 18:20:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:20:00,5,C-3,228.04
491,C,3,"[2016-10-29 18:40:00,2016-10-29 19:00:00)",2016-10-29 18:40:00,2016-10-29,1025.1,1030.3,355.0,2.3,12.8,84.0,0.0,18:40:00,5,C-3,138.78
492,C,3,"[2016-10-30 17:00:00,2016-10-30 17:20:00)",2016-10-30 17:00:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:00:00,6,C-3,232.71
493,C,3,"[2016-10-30 17:20:00,2016-10-30 17:40:00)",2016-10-30 17:20:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:20:00,6,C-3,218.07
494,C,3,"[2016-10-30 17:40:00,2016-10-30 18:00:00)",2016-10-30 17:40:00,2016-10-30,1020.6,1025.8,313.0,1.3,15.7,78.0,0.0,17:40:00,6,C-3,225.89
495,C,3,"[2016-10-30 18:00:00,2016-10-30 18:20:00)",2016-10-30 18:00:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:00:00,6,C-3,226.33
496,C,3,"[2016-10-30 18:20:00,2016-10-30 18:40:00)",2016-10-30 18:20:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:20:00,6,C-3,159.06
497,C,3,"[2016-10-30 18:40:00,2016-10-30 19:00:00)",2016-10-30 18:40:00,2016-10-30,1019.3,1024.4,320.0,1.7,15.2,85.0,0.0,18:40:00,6,C-3,215.88
498,C,3,"[2016-10-31 17:00:00,2016-10-31 17:20:00)",2016-10-31 17:00:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:00:00,0,C-3,108.04
499,C,3,"[2016-10-31 17:20:00,2016-10-31 17:40:00)",2016-10-31 17:20:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:20:00,0,C-3,158.86
500,C,3,"[2016-10-31 17:40:00,2016-10-31 18:00:00)",2016-10-31 17:40:00,2016-10-31,1025.0,1030.2,0.0,4.5,14.5,83.0,0.0,17:40:00,0,C-3,215.31
501,C,3,"[2016-10-31 18:00:00,2016-10-31 18:20:00)",2016-10-31 18:00:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:00:00,0,C-3,192.58
502,C,3,"[2016-10-31 18:20:00,2016-10-31 18:40:00)",2016-10-31 18:20:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:20:00,0,C-3,158.13
503,C,3,"[2016-10-31 18:40:00,2016-10-31 19:00:00)",2016-10-31 18:40:00,2016-10-31,1024.7,1029.9,360.0,4.1,14.1,85.0,0.0,18:40:00,0,C-3,177.77

In [40]:
test_for_last20min[test_for_last20min['avg_travel_time'].isnull()]

Empty DataFrame
Columns: [intersection_id, tollgate_id, time_window, start_time, date, pressure, sea_pressure, wind_direction, wind_speed, temperature, rel_humidity, precipitation, time, weekday, route, avg_travel_time]
Index: []

In [14]:
last_travel_time = test_for_last20min['avg_travel_time']
last_20min = last_travel_time.copy()
last_40min = last_travel_time.copy()
last_60min = last_travel_time.copy()
last_80min = last_travel_time.copy()
last_100min = last_travel_time.copy()
last_120min = last_travel_time.copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(last_travel_time)):
    if i % 6 == 0:
        last_20min[i] = last_travel_time[i+5]
        last_40min[i] = last_travel_time[i+4]
        last_60min[i] = last_travel_time[i+3]
        last_80min[i] = last_travel_time[i+2]
        last_100min[i] = last_travel_time[i+1]
        last_120min[i] = last_travel_time[i]
    if i % 6 == 1:
        last_40min[i] = last_travel_time[i+4]
        last_60min[i] = last_travel_time[i+3]
        last_80min[i] = last_travel_time[i+2]
        last_100min[i] = last_travel_time[i+1]
        last_120min[i] = last_travel_time[i]
    if i % 6 == 2:
        last_60min[i] = last_travel_time[i+3]
        last_80min[i] = last_travel_time[i+2]
        last_100min[i] = last_travel_time[i+1]
        last_120min[i] = last_travel_time[i]
    if i % 6 == 3:
        last_80min[i] = last_travel_time[i+2]
        last_100min[i] = last_travel_time[i+1]
        last_120min[i] = last_travel_time[i]
    if i % 6 == 4:
        last_100min[i] = last_travel_time[i+1]
        last_120min[i] = last_travel_time[i] 
    if i % 6 == 5:
        last_120min[i] = last_travel_time[i]
test_travel_time['last_20min'] = last_20min
test_travel_time['last_40min'] = last_40min
test_travel_time['last_60min'] = last_60min
test_travel_time['last_80min'] = last_80min
test_travel_time['last_100min'] = last_100min
test_travel_time['last_120min'] = last_120min
test_travel_time

,intersection_id,tollgate_id,time_window,start_time,date,pressure,sea_pressure,wind_direction,wind_speed,temperature,...,precipitation,time,weekday,route,last_20min,last_40min,last_60min,last_80min,last_100min,last_120min
0,A,2,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",2016-10-18 08:00:00,2016-10-18,1012.5,1017.5,128.0,1.6,23.4,...,0.0,08:00:00,1,A-2,63.60,56.17,52.61,68.02,43.68,41.10
1,A,2,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",2016-10-18 08:20:00,2016-10-18,1012.5,1017.5,128.0,1.6,23.4,...,0.0,08:20:00,1,A-2,NaN,63.60,56.17,52.61,68.02,43.68
2,A,2,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",2016-10-18 08:40:00,2016-10-18,1012.5,1017.5,128.0,1.6,23.4,...,0.0,08:40:00,1,A-2,NaN,NaN,63.60,56.17,52.61,68.02
3,A,2,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",2016-10-18 09:00:00,2016-10-18,1013.0,1018.0,205.0,0.6,20.9,...,1.8,09:00:00,1,A-2,NaN,NaN,NaN,63.60,56.17,52.61
4,A,2,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",2016-10-18 09:20:00,2016-10-18,1013.0,1018.0,205.0,0.6,20.9,...,1.8,09:20:00,1,A-2,NaN,NaN,NaN,NaN,63.60,56.17
5,A,2,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",2016-10-18 09:40:00,2016-10-18,1013.0,1018.0,205.0,0.6,20.9,...,1.8,09:40:00,1,A-2,NaN,NaN,NaN,NaN,NaN,63.60
6,A,2,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",2016-10-19 08:00:00,2016-10-19,1010.8,1015.8,89.0,2.1,20.7,...,1.0,08:00:00,2,A-2,58.29,100.11,69.58,37.41,57.01,40.01
7,A,2,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",2016-10-19 08:20:00,2016-10-19,1010.8,1015.8,89.0,2.1,20.7,...,1.0,08:20:00,2,A-2,NaN,58.29,100.11,69.58,37.41,57.01
8,A,2,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",2016-10-19 08:40:00,2016-10-19,1010.8,1015.8,89.0,2.1,20.7,...,1.0,08:40:00,2,A-2,NaN,NaN,58.29,100.11,69.58,37.41
9,A,2,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",2016-10-19 09:00:00,2016-10-19,1010.9,1015.9,96.0,1.8,20.5,...,0.2,09:00:00,2,A-2,NaN,NaN,NaN,58.29,100.11,69.58
10,A,2,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",2016-10-19 09:20:00,2016-10-19,1010.9,1015.9,96.0,1.8,20.5,...,0.2,09:20:00,2,A-2,NaN,NaN,NaN,NaN,58.29,100.11
11,A,2,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",2016-10-19 09:40:00,2016-10-19,1010.9,1015.9,96.0,1.8,20.5,...,0.2,09:40:00,2,A-2,NaN,NaN,NaN,NaN,NaN,58.29
12,A,2,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",2016-10-20 08:00:00,2016-10-20,1007.8,1012.8,94.0,2.7,22.3,...,0.0,08:00:00,3,A-2,75.79,62.99,74.07,60.88,49.79,63.58
13,A,2,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",2016-10-20 08:20:00,2016-10-20,1007.8,1012.8,94.0,2.7,22.3,...,0.0,08:20:00,3,A-2,NaN,75.79,62.99,74.07,60.88,49.79
14,A,2,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",2016-10-20 08:40:00,2016-10-20,1007.8,1012.8,94.0,2.7,22.3,...,0.0,08:40:00,3,A-2,NaN,NaN,75.79,62.99,74.07,60.88
15,A,2,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",2016-10-20 09:00:00,2016-10-20,1008.1,1013.1,96.0,2.0,22.4,...,0.0,09:00:00,3,A-2,NaN,NaN,NaN,75.79,62.99,74.07
16,A,2,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",2016-10-20 09:20:00,2016-10-20,1008.1,1013.1,96.0,2.0,22.4,...,0.0,09:20:00,3,A-2,NaN,NaN,NaN,NaN,75.79,62.99
17,A,2,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",2016-10-20 09:40:00,2016-10-20,1008.1,1013.1,96.0,2.0,22.4,...,0.0,09:40:00,3,A-2,NaN,NaN,NaN,NaN,NaN,75.79
18,A,2,"[2016-10-21 08:00:00,2016-10-21 08:20:00)",2016-10-21 08:00:00,2016-10-21,1004.1,1009.1,335.0,3.1,21.4,...,0.5,08:00:00,4,A-2,75.14,55.85,49.87,48.95,40.73,60.93
19,A,2,"[2016-10-21 08:20:00,2016-10-21 08:40:00)",2016-10-21 08:20:00,2016-10-21,1004.1,1009.1,335.0,3.1,21.4,...,0.5,08:20:00,4,A-2,NaN,75.14,55.85,49.87,48.95,40.73
20,A,2,"[2016-10-21 08:40:00,2016-10-21 09:00:00)",2016-10-21 08:40:00,2016-10-21,1004.1,1009.1,335.0,3.1,21.4,...,0.5,08:40:00,4,A-2,NaN,NaN,75.14,55.85,49.87,48.95
21,A,2,"[2016-10-21 09:00:00,2016-10-21 09:20:00)",2016-10-21 09:00:00,2016-10-21,1004.3,1009.3,340.0,2.8,21.2,...,0.0,09:00:00,4,A-2,NaN,NaN,NaN,75.14,55.85,49.87
22,A,2,"[2016-10-21 09:20:00,2016-10-21 09:40:00)",2016-10-21 09:20:00,2016-10-21,1004.3,1009.3,340.0,2.8,21.2,...,0.0,09:20:00,4,A-2,NaN,NaN,NaN,NaN,75.14,55.85
23,A,2,"[2016-10-21 09:40:00,2016-10-21 10:00:00)",2016-10-21 09:40:00,2016-10-21,1004.3,1009.3,340.0,2.8,21.2,...,0.0,09:40:00,4,A-2,NaN,NaN,NaN,NaN,NaN,75.14
24,A,2,"[2016-10-22 08:00:00,2016-10-22 08:20:00)",2016-10-22 08:00:00,2016-10-22,1000.2,1005.1,86.0,2.9,22.6,...,0.1,08:00:00,5,A-2,90.94,58.39,51.07,52.29,81.57,33.68
25,A,2,"[2016-10-22 08:20:00,2016-10-22 08:40:00)",2016-10-22 08:20:00,2016-10-22,1000.2,1005.1,86.0,2.9,22.6,...,0.1,08:20:00,5,A-2,NaN,90.94,58.39,51.07,52.29,81.57
26,A,2,"[2016-10-22 08:40:00,2016-10-22 09:00:00)",2016-10-22 08:40:00,2016-10-22,1000.2,1005.1,86.0,2.9,22.6,...,0.1,08:40:00,5,A-2,NaN,NaN,90.94,58.39,51.07,52.29
27,A,2,"[2016-10-22 09:00:00,2016-10-22 09:20:00)",2016-10-22 09:00:00,2016-10-22,999.4,1004.3,117.0,2.0,22.8,...,3.1,09:00:00,5,A-2,NaN,NaN,NaN,90.94,58.39,51.07
28,A,2,"[2016-10-22 09:20:00,2016-10-22 09:40:00)",2016-10-22 09:20:00,2016-10-22,999.4,1004.3,117.0,2.0,22.8,...,3.1,09:20:00,5,A-2,NaN,NaN,NaN,NaN,90.94,58.39
29,A,2,"[2016-10-22 09:40:00,2016-10-22 10:00:00)",2016-10-22 09:40:00,2016-10-22,999.4,1004.3,117.0,2.0,22.8,...,3.1,09:40:00,5,A-2,NaN,NaN,NaN,NaN,NaN,90.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,C,3,"[2016-10-20 17:00:00,2016-10-20 17:20:00)",2016-10-20 17:00:00,2016-10-20,1008.5,1013.5,67.0,1.6,21.5,...,1.0,17:00:00,3,C-3,164.04,147.22,164.89,141.89,142.73,148.00
475,C,3,"[2016-10-20 17:20:00,2016-10-20 17:40:00)",2016-10-20 17:20:00,2016-10-20,1008.5,1013.5,67.0,1.6,21.5,...,1.0,17:20:00,3,C-3,NaN,164.04,147.22,164.89,141.89,142.73
476,C,3,"[2016-10-20 17:40:00,2016-10-20 18:00:00)",2016-10-20 17:40:00,2016-10-20,1008.5,1013.5,67.0,1.6,21.5,...,1.0,17:40:00,3,C-3,NaN,NaN,164.04,147.22,164.89,141.89
477,C,3,"[2016-10-20 18:00:00,2016-10-20 18:20:00)",2016-10-20 18:00:00,2016-10-20,1007.3,1012.3,94.0,1.6,21.7,...,0.0,18:00:00,3,C-3,NaN,NaN,NaN,164.04,147.22,164.89
478,C,3,"[2016-10-20 18:20:00,2016-10-20 18:40:00)",2016-10-20 18:20:00,2016-10-20,1007.3,1012.3,94.0,1.6,21.7,...,0.0,18:20:00,3,C-3,NaN,NaN,NaN,NaN,164.04,147.22
479,C,3,"[2016-10-20 18:40:00,2016-10-20 19:00:00)",2016-10-20 18:40:00,2016-10-20,1007.3,1012.3,94.0,1.6,21.7,...,0.0,18:40:00,3,C-3,NaN,NaN,NaN,NaN,NaN,164.04
480,C,3,"[2016-10-21 17:00:00,2016-10-21 17:20:00)",2016-10-21 17:00:00,2016-10-21,1005.8,1010.8,357.0,2.1,21.1,...,0.0,17:00:00,4,C-3,179.66,128.55,192.84,99.47,190.87,184.32
481,C,3,"[2016-10-21 17:20:00,2016-10-21 17:40:00)",2016-10-21 17:20:00,2016-10-21,1005.8,1010.8,357.0,2.1,21.1,...,0.0,17:20:00,4,C-3,NaN,179.66,128.55,192.84,99.47,190.87
482,C,3,"[2016-10-21 17:40:00,2016-10-21 18:00:00)",2016-10-21 17:40:00,2016-10-21,1005.8,1010.8,357.0,2.1,21.1,...,0.0,17:40:00,4,C-3,NaN,NaN,179.66,128.55,192.84,99.47
483,C,3,"[2016-10-21 18:00:00,2016-10-21 18:20:00)",2016-10-21 18:00:00,2016-10-21,1005.3,1010.3,342.0,2.5,21.0,...,1.3,18:00:00,4,C-3,NaN,NaN,NaN,179.66,128.55,192.84
484,C,3,"[2016-10-21 18:20:00,2016-10-21 18:40:00)",2016-10-21 18:20:00,2016-10-21,1005.3,1010.3,342.0,2.5,21.0,...,1.3,18:20:00,4,C-3,NaN,NaN,NaN,NaN,179.66,128.55
485,C,3,"[2016-10-21 18:40:00,2016-10-21 19:00:00)",2016-10-21 18:40:00,2016-10-21,1005.3,1010.3,342.0,2.5,21.0,...,1.3,18:40:00,4,C-3,NaN,NaN,NaN,NaN,NaN,179.66
486,C,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",2016-10-22 17:00:00,2016-10-22,1004.0,1009.0,352.0,4.8,20.7,...,1.6,17:00:00,5,C-3,121.43,170.00,223.71,294.56,256.40,NaN
487,C,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",2016-10-22 17:20:00,2016-10-22,1004.0,1009.0,352.0,4.8,20.7,...,1.6,17:20:00,5,C-3,NaN,121.43,170.00,223.71,294.56,256.40
488,C,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",2016-10-22 17:40:00,2016-10-22,1004.0,1009.0,352.0,4.8,20.7,...,1.6,17:40:00,5,C-3,NaN,NaN,121.43,170.00,223.71,294.56
489,C,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",2016-10-22 18:00:00,2016-10-22,1005.3,1010.3,0.0,6.0,20.8,...,0.0,18:00:00,5,C-3,NaN,NaN,NaN,121.43,170.00,223.71
490,C,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",2016-10-22 18:20:00,2016-10-22,1005.3,1010.3,0.0,6.0,20.8,...,0.0,18:20:00,5,C-3,NaN,NaN,NaN,NaN,121.43,170.00
491,C,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",2016-10-22 18:40:00,2016-10-22,1005.3,1010.3,0.0,6.0,20.8,...,0.0,18:40:00,5,C-3,NaN,NaN,NaN,NaN,NaN,121.43
492,C,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",2016-10-23 17:00:00,2016-10-23,1011.4,1016.4,326.0,1.1,19.7,...,0.0,17:00:00,6,C-3,135.46,197.32,224.29,172.49,151.95,163.58
493,C,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",2016-10-23 17:20:00,2016-10-23,1011.4,1016.4,326.0,1.1,19.7,...,0.0,17:20:00,6,C-3,NaN,135.46,197.32,224.29,172.49,151.95
494,C,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",2016-10-23 17:40:00,2016-10-23,1011.4,1016.4,326.0,1.1,19.7,...,0.0,17:40:00,6,C-3,NaN,NaN,135.46,197.32,224.29,172.49
495,C,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",2016-10-23 18:00:00,2016-10-23,1011.0,1016.0,43.0,0.8,19.3,...,0.0,18:00:00,6,C-3,NaN,NaN,NaN,135.46,197.32,224.29
496,C,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",2016-10-23 18:20:00,2016-10-23,1011.0,1016.0,43.0,0.8,19.3,...,0.0,18:20:00,6,C-3,NaN,NaN,NaN,NaN,135.46,197.32
497,C,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",2016-10-23 18:40:00,2016-10-23,1011.0,1016.0,43.0,0.8,19.3,...,0.0,18:40:00,6,C-3,NaN,NaN,NaN,NaN,NaN,135.46
498,C,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",2016-10-24 17:00:00,2016-10-24,1008.0,1013.0,210.0,1.4,21.0,...,0.0,17:00:00,0,C-3,159.81,NaN,159.37,203.97,144.68,183.31
499,C,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",2016-10-24 17:20:00,2016-10-24,1008.0,1013.0,210.0,1.4,21.0,...,0.0,17:20:00,0,C-3,NaN,159.81,NaN,159.37,203.97,144.68
500,C,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",2016-10-24 17:40:00,2016-10-24,1008.0,1013.0,210.0,1.4,21.0,...,0.0,17:40:00,0,C-3,NaN,NaN,159.81,NaN,159.37,203.97
501,C,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",2016-10-24 18:00:00,2016-10-24,1007.3,1012.3,226.0,3.0,20.7,...,0.0,18:00:00,0,C-3,NaN,NaN,NaN,159.81,NaN,159.37
502,C,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",2016-10-24 18:20:00,2016-10-24,1007.3,1012.3,226.0,3.0,20.7,...,0.0,18:20:00,0,C-3,NaN,NaN,NaN,NaN,159.81,NaN
503,C,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",2016-10-24 18:40:00,2016-10-24,1007.3,1012.3,226.0,3.0,20.7,...,0.0,18:40:00,0,C-3,NaN,NaN,NaN,NaN,NaN,159.81

In [35]:
# timemap特征
# 把time映射成1～72
from collections import defaultdict
time_start = datetime(2016,10,17,0,0,0)
timedic = defaultdict(int)
for i in range(72):
    timedic[time_start.time()] = i+1
    time_start = time_start + timedelta(minutes=20)
test_travel_time['timemap'] = test_travel_time['time'].map(lambda x:timedic[x])

In [36]:
# 写出数据
test_travel_time.to_csv('test_travel_time_feature_ffill.csv', index=False)

### 生成流量测试特征集

In [19]:
in_file_path = '/home/godcedric/GitLocal/KDDCUP2017/result/test1_20min_avg_volume.csv'
test2 = pd.read_csv(in_file_path)
test_volume = pd.read_csv('/home/godcedric/GitLocal/KDDCUP2017/submission_sample/submission_sample_volume.csv')

In [21]:
del test_volume['volume']

In [17]:
# start_time特征
test_volume['start_time'] = test_volume['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:],'%Y-%m-%d %H:%M:%S'))

In [18]:
test_volume = test_volume.sort(['tollgate_id','direction','start_time'])
test_volume

/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

,tollgate_id,time_window,direction,start_time
0,1,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",0,2016-10-18 08:00:00
7,1,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",0,2016-10-18 08:20:00
14,1,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",0,2016-10-18 08:40:00
21,1,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",0,2016-10-18 09:00:00
28,1,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",0,2016-10-18 09:20:00
35,1,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",0,2016-10-18 09:40:00
210,1,"[2016-10-18 17:00:00,2016-10-18 17:20:00)",0,2016-10-18 17:00:00
217,1,"[2016-10-18 17:20:00,2016-10-18 17:40:00)",0,2016-10-18 17:20:00
224,1,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",0,2016-10-18 17:40:00
231,1,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",0,2016-10-18 18:00:00
238,1,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",0,2016-10-18 18:20:00
245,1,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",0,2016-10-18 18:40:00
1,1,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",0,2016-10-19 08:00:00
8,1,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",0,2016-10-19 08:20:00
15,1,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",0,2016-10-19 08:40:00
22,1,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",0,2016-10-19 09:00:00
29,1,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",0,2016-10-19 09:20:00
36,1,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",0,2016-10-19 09:40:00
211,1,"[2016-10-19 17:00:00,2016-10-19 17:20:00)",0,2016-10-19 17:00:00
218,1,"[2016-10-19 17:20:00,2016-10-19 17:40:00)",0,2016-10-19 17:20:00
225,1,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",0,2016-10-19 17:40:00
232,1,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",0,2016-10-19 18:00:00
239,1,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",0,2016-10-19 18:20:00
246,1,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",0,2016-10-19 18:40:00
2,1,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",0,2016-10-20 08:00:00
9,1,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",0,2016-10-20 08:20:00
16,1,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",0,2016-10-20 08:40:00
23,1,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",0,2016-10-20 09:00:00
30,1,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",0,2016-10-20 09:20:00
37,1,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",0,2016-10-20 09:40:00
...,...,...,...,...
382,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",1,2016-10-22 17:00:00
389,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",1,2016-10-22 17:20:00
396,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",1,2016-10-22 17:40:00
403,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",1,2016-10-22 18:00:00
410,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",1,2016-10-22 18:20:00
417,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",1,2016-10-22 18:40:00
173,3,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",1,2016-10-23 08:00:00
180,3,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",1,2016-10-23 08:20:00
187,3,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",1,2016-10-23 08:40:00
194,3,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",1,2016-10-23 09:00:00
201,3,"[2016-10-23 09:20:00,2016-10-23 09:40:00)",1,2016-10-23 09:20:00
208,3,"[2016-10-23 09:40:00,2016-10-23 10:00:00)",1,2016-10-23 09:40:00
383,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",1,2016-10-23 17:00:00
390,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",1,2016-10-23 17:20:00
397,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",1,2016-10-23 17:40:00
404,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",1,2016-10-23 18:00:00
411,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",1,2016-10-23 18:20:00
418,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",1,2016-10-23 18:40:00
174,3,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",1,2016-10-24 08:00:00
181,3,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",1,2016-10-24 08:20:00
188,3,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",1,2016-10-24 08:40:00
195,3,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",1,2016-10-24 09:00:00
202,3,"[2016-10-24 09:20:00,2016-10-24 09:40:00)",1,2016-10-24 09:20:00
209,3,"[2016-10-24 09:40:00,2016-10-24 10:00:00)",1,2016-10-24 09:40:00
384,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",1,2016-10-24 17:00:00
391,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",1,2016-10-24 17:20:00
398,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",1,2016-10-24 17:40:00
405,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",1,2016-10-24 18:00:00
412,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",1,2016-10-24 18:20:00
419,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",1,2016-10-24 18:40:00

In [19]:
# pair特征
test_volume['pair'] = test_volume['tollgate_id'].astype(str) + '-' + test_volume['direction'].astype(str)

In [20]:
# 天气特征
test_volume = pd.merge(test_volume, weather_data, on='start_time', how='left')

In [21]:
# 星期几
test_volume['weekday'] = test_volume['start_time'].map(lambda x: x.weekday())

In [22]:
# 时间窗口
test_volume['time'] = test_volume['start_time'].map(lambda x: x.time())

In [23]:
del test_volume['hour']

In [27]:
# last_20min
test2['start_time'] = test2['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:], '%Y-%m-%d %H:%M:%S')+timedelta(hours=2))
del test2['time_window']

In [28]:
del test2['etc']

In [29]:
test2 = test2.sort(['tollgate_id','direction'])

/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [30]:
test2

     tollgate_id  direction  volume          start_time
252            1          0      13 2016-10-18 08:00:00
253            1          0      17 2016-10-18 08:20:00
254            1          0      21 2016-10-18 08:40:00
255            1          0      31 2016-10-18 09:00:00
256            1          0      28 2016-10-18 09:20:00
257            1          0      47 2016-10-18 09:40:00
258            1          0      52 2016-10-18 17:00:00
259            1          0      38 2016-10-18 17:20:00
260            1          0      35 2016-10-18 17:40:00
261            1          0      57 2016-10-18 18:00:00
262            1          0      45 2016-10-18 18:20:00
263            1          0      53 2016-10-18 18:40:00
264            1          0      12 2016-10-19 08:00:00
265            1          0      16 2016-10-19 08:20:00
266            1          0      17 2016-10-19 08:40:00
267            1          0      22 2016-10-19 09:00:00
268            1          0      38 2016-10-19 09:20:00
269            1          0      41 2016-10-19 09:40:00
270            1          0      40 2016-10-19 17:00:00
271            1          0      34 2016-10-19 17:20:00
272            1          0      50 2016-10-19 17:40:00
273            1          0      39 2016-10-19 18:00:00
274            1          0      40 2016-10-19 18:20:00
275            1          0      36 2016-10-19 18:40:00
276            1          0       8 2016-10-20 08:00:00
277            1          0      16 2016-10-20 08:20:00
278            1          0      23 2016-10-20 08:40:00
279            1          0      22 2016-10-20 09:00:00
280            1          0      33 2016-10-20 09:20:00
281            1          0      37 2016-10-20 09:40:00
..           ...        ...     ...                 ...
222            3          1      73 2016-10-22 17:00:00
223            3          1      82 2016-10-22 17:20:00
224            3          1      97 2016-10-22 17:40:00
225            3          1      94 2016-10-22 18:00:00
226            3          1      72 2016-10-22 18:20:00
227            3          1      87 2016-10-22 18:40:00
228            3          1       9 2016-10-23 08:00:00
229            3          1      19 2016-10-23 08:20:00
230            3          1      33 2016-10-23 08:40:00
231            3          1      36 2016-10-23 09:00:00
232            3          1      53 2016-10-23 09:20:00
233            3          1      51 2016-10-23 09:40:00
234            3          1     137 2016-10-23 17:00:00
235            3          1     117 2016-10-23 17:20:00
236            3          1      89 2016-10-23 17:40:00
237            3          1      95 2016-10-23 18:00:00
238            3          1      91 2016-10-23 18:20:00
239            3          1     104 2016-10-23 18:40:00
240            3          1      23 2016-10-24 08:00:00
241            3          1      41 2016-10-24 08:20:00
242            3          1      60 2016-10-24 08:40:00
243            3          1      75 2016-10-24 09:00:00
244            3          1     101 2016-10-24 09:20:00
245            3          1      99 2016-10-24 09:40:00
246            3          1      80 2016-10-24 17:00:00
247            3          1     102 2016-10-24 17:20:00
248            3          1      71 2016-10-24 17:40:00
249            3          1     101 2016-10-24 18:00:00
250            3          1      80 2016-10-24 18:20:00
251            3          1      81 2016-10-24 18:40:00

[420 rows x 4 columns]

In [31]:
test_for_last20min2 = pd.merge(test_volume, test2, on=['tollgate_id','direction','start_time'], how='left')

In [32]:
# 无缺失值

In [33]:
last_volume = test_for_last20min2['volume']
last_20min = last_volume.copy()
last_40min = last_volume.copy()
last_60min = last_volume.copy()
last_80min = last_volume.copy()
last_100min = last_volume.copy()
last_120min = last_volume.copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(last_volume)):
    if i % 6 == 0:
        last_20min[i] = last_volume[i+5]
        last_40min[i] = last_volume[i+4]
        last_60min[i] = last_volume[i+3]
        last_80min[i] = last_volume[i+2]
        last_100min[i] = last_volume[i+1]
        last_120min[i] = last_volume[i]
    if i % 6 == 1:
        last_40min[i] = last_volume[i+4]
        last_60min[i] = last_volume[i+3]
        last_80min[i] = last_volume[i+2]
        last_100min[i] = last_volume[i+1]
        last_120min[i] = last_volume[i]
    if i % 6 == 2:
        last_60min[i] = last_volume[i+3]
        last_80min[i] = last_volume[i+2]
        last_100min[i] = last_volume[i+1]
        last_120min[i] = last_volume[i]
    if i % 6 == 3:
        last_80min[i] = last_volume[i+2]
        last_100min[i] = last_volume[i+1]
        last_120min[i] = last_volume[i]
    if i % 6 == 4:
        last_100min[i] = last_volume[i+1]
        last_120min[i] = last_volume[i] 
    if i % 6 == 5:
        last_120min[i] = last_volume[i]
test_volume['last_20min'] = last_20min
test_volume['last_40min'] = last_40min
test_volume['last_60min'] = last_60min
test_volume['last_80min'] = last_80min
test_volume['last_100min'] = last_100min
test_volume['last_120min'] = last_120min
test_volume

,tollgate_id,time_window,direction,start_time,pair,date,pressure,sea_pressure,wind_direction,wind_speed,...,rel_humidity,precipitation,weekday,time,last_20min,last_40min,last_60min,last_80min,last_100min,last_120min
0,1,"[2016-10-18 08:00:00,2016-10-18 08:20:00)",0,2016-10-18 08:00:00,1-0,2016-10-18,1012.5,1017.5,128.0,1.6,...,73.0,0.0,1,08:00:00,47.0,28.0,31.0,21.0,17.0,13.0
1,1,"[2016-10-18 08:20:00,2016-10-18 08:40:00)",0,2016-10-18 08:20:00,1-0,2016-10-18,1012.5,1017.5,128.0,1.6,...,73.0,0.0,1,08:20:00,NaN,47.0,28.0,31.0,21.0,17.0
2,1,"[2016-10-18 08:40:00,2016-10-18 09:00:00)",0,2016-10-18 08:40:00,1-0,2016-10-18,1012.5,1017.5,128.0,1.6,...,73.0,0.0,1,08:40:00,NaN,NaN,47.0,28.0,31.0,21.0
3,1,"[2016-10-18 09:00:00,2016-10-18 09:20:00)",0,2016-10-18 09:00:00,1-0,2016-10-18,1013.0,1018.0,205.0,0.6,...,94.0,1.8,1,09:00:00,NaN,NaN,NaN,47.0,28.0,31.0
4,1,"[2016-10-18 09:20:00,2016-10-18 09:40:00)",0,2016-10-18 09:20:00,1-0,2016-10-18,1013.0,1018.0,205.0,0.6,...,94.0,1.8,1,09:20:00,NaN,NaN,NaN,NaN,47.0,28.0
5,1,"[2016-10-18 09:40:00,2016-10-18 10:00:00)",0,2016-10-18 09:40:00,1-0,2016-10-18,1013.0,1018.0,205.0,0.6,...,94.0,1.8,1,09:40:00,NaN,NaN,NaN,NaN,NaN,47.0
6,1,"[2016-10-18 17:00:00,2016-10-18 17:20:00)",0,2016-10-18 17:00:00,1-0,2016-10-18,1013.7,1018.7,90.0,1.9,...,95.0,0.1,1,17:00:00,53.0,45.0,57.0,35.0,38.0,52.0
7,1,"[2016-10-18 17:20:00,2016-10-18 17:40:00)",0,2016-10-18 17:20:00,1-0,2016-10-18,1013.7,1018.7,90.0,1.9,...,95.0,0.1,1,17:20:00,NaN,53.0,45.0,57.0,35.0,38.0
8,1,"[2016-10-18 17:40:00,2016-10-18 18:00:00)",0,2016-10-18 17:40:00,1-0,2016-10-18,1013.7,1018.7,90.0,1.9,...,95.0,0.1,1,17:40:00,NaN,NaN,53.0,45.0,57.0,35.0
9,1,"[2016-10-18 18:00:00,2016-10-18 18:20:00)",0,2016-10-18 18:00:00,1-0,2016-10-18,1012.1,1017.1,125.0,2.3,...,96.0,1.3,1,18:00:00,NaN,NaN,NaN,53.0,45.0,57.0
10,1,"[2016-10-18 18:20:00,2016-10-18 18:40:00)",0,2016-10-18 18:20:00,1-0,2016-10-18,1012.1,1017.1,125.0,2.3,...,96.0,1.3,1,18:20:00,NaN,NaN,NaN,NaN,53.0,45.0
11,1,"[2016-10-18 18:40:00,2016-10-18 19:00:00)",0,2016-10-18 18:40:00,1-0,2016-10-18,1012.1,1017.1,125.0,2.3,...,96.0,1.3,1,18:40:00,NaN,NaN,NaN,NaN,NaN,53.0
12,1,"[2016-10-19 08:00:00,2016-10-19 08:20:00)",0,2016-10-19 08:00:00,1-0,2016-10-19,1010.8,1015.8,89.0,2.1,...,94.0,1.0,2,08:00:00,41.0,38.0,22.0,17.0,16.0,12.0
13,1,"[2016-10-19 08:20:00,2016-10-19 08:40:00)",0,2016-10-19 08:20:00,1-0,2016-10-19,1010.8,1015.8,89.0,2.1,...,94.0,1.0,2,08:20:00,NaN,41.0,38.0,22.0,17.0,16.0
14,1,"[2016-10-19 08:40:00,2016-10-19 09:00:00)",0,2016-10-19 08:40:00,1-0,2016-10-19,1010.8,1015.8,89.0,2.1,...,94.0,1.0,2,08:40:00,NaN,NaN,41.0,38.0,22.0,17.0
15,1,"[2016-10-19 09:00:00,2016-10-19 09:20:00)",0,2016-10-19 09:00:00,1-0,2016-10-19,1010.9,1015.9,96.0,1.8,...,95.0,0.2,2,09:00:00,NaN,NaN,NaN,41.0,38.0,22.0
16,1,"[2016-10-19 09:20:00,2016-10-19 09:40:00)",0,2016-10-19 09:20:00,1-0,2016-10-19,1010.9,1015.9,96.0,1.8,...,95.0,0.2,2,09:20:00,NaN,NaN,NaN,NaN,41.0,38.0
17,1,"[2016-10-19 09:40:00,2016-10-19 10:00:00)",0,2016-10-19 09:40:00,1-0,2016-10-19,1010.9,1015.9,96.0,1.8,...,95.0,0.2,2,09:40:00,NaN,NaN,NaN,NaN,NaN,41.0
18,1,"[2016-10-19 17:00:00,2016-10-19 17:20:00)",0,2016-10-19 17:00:00,1-0,2016-10-19,1011.6,1016.6,61.0,1.2,...,96.0,1.5,2,17:00:00,36.0,40.0,39.0,50.0,34.0,40.0
19,1,"[2016-10-19 17:20:00,2016-10-19 17:40:00)",0,2016-10-19 17:20:00,1-0,2016-10-19,1011.6,1016.6,61.0,1.2,...,96.0,1.5,2,17:20:00,NaN,36.0,40.0,39.0,50.0,34.0
20,1,"[2016-10-19 17:40:00,2016-10-19 18:00:00)",0,2016-10-19 17:40:00,1-0,2016-10-19,1011.6,1016.6,61.0,1.2,...,96.0,1.5,2,17:40:00,NaN,NaN,36.0,40.0,39.0,50.0
21,1,"[2016-10-19 18:00:00,2016-10-19 18:20:00)",0,2016-10-19 18:00:00,1-0,2016-10-19,1010.1,1015.1,325.0,0.5,...,97.0,0.1,2,18:00:00,NaN,NaN,NaN,36.0,40.0,39.0
22,1,"[2016-10-19 18:20:00,2016-10-19 18:40:00)",0,2016-10-19 18:20:00,1-0,2016-10-19,1010.1,1015.1,325.0,0.5,...,97.0,0.1,2,18:20:00,NaN,NaN,NaN,NaN,36.0,40.0
23,1,"[2016-10-19 18:40:00,2016-10-19 19:00:00)",0,2016-10-19 18:40:00,1-0,2016-10-19,1010.1,1015.1,325.0,0.5,...,97.0,0.1,2,18:40:00,NaN,NaN,NaN,NaN,NaN,36.0
24,1,"[2016-10-20 08:00:00,2016-10-20 08:20:00)",0,2016-10-20 08:00:00,1-0,2016-10-20,1007.8,1012.8,94.0,2.7,...,91.0,0.0,3,08:00:00,37.0,33.0,22.0,23.0,16.0,8.0
25,1,"[2016-10-20 08:20:00,2016-10-20 08:40:00)",0,2016-10-20 08:20:00,1-0,2016-10-20,1007.8,1012.8,94.0,2.7,...,91.0,0.0,3,08:20:00,NaN,37.0,33.0,22.0,23.0,16.0
26,1,"[2016-10-20 08:40:00,2016-10-20 09:00:00)",0,2016-10-20 08:40:00,1-0,2016-10-20,1007.8,1012.8,94.0,2.7,...,91.0,0.0,3,08:40:00,NaN,NaN,37.0,33.0,22.0,23.0
27,1,"[2016-10-20 09:00:00,2016-10-20 09:20:00)",0,2016-10-20 09:00:00,1-0,2016-10-20,1008.1,1013.1,96.0,2.0,...,91.0,0.0,3,09:00:00,NaN,NaN,NaN,37.0,33.0,22.0
28,1,"[2016-10-20 09:20:00,2016-10-20 09:40:00)",0,2016-10-20 09:20:00,1-0,2016-10-20,1008.1,1013.1,96.0,2.0,...,91.0,0.0,3,09:20:00,NaN,NaN,NaN,NaN,37.0,33.0
29,1,"[2016-10-20 09:40:00,2016-10-20 10:00:00)",0,2016-10-20 09:40:00,1-0,2016-10-20,1008.1,1013.1,96.0,2.0,...,91.0,0.0,3,09:40:00,NaN,NaN,NaN,NaN,NaN,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
390,3,"[2016-10-22 17:00:00,2016-10-22 17:20:00)",1,2016-10-22 17:00:00,3-1,2016-10-22,1004.0,1009.0,352.0,4.8,...,96.0,1.6,5,17:00:00,87.0,72.0,94.0,97.0,82.0,73.0
391,3,"[2016-10-22 17:20:00,2016-10-22 17:40:00)",1,2016-10-22 17:20:00,3-1,2016-10-22,1004.0,1009.0,352.0,4.8,...,96.0,1.6,5,17:20:00,NaN,87.0,72.0,94.0,97.0,82.0
392,3,"[2016-10-22 17:40:00,2016-10-22 18:00:00)",1,2016-10-22 17:40:00,3-1,2016-10-22,1004.0,1009.0,352.0,4.8,...,96.0,1.6,5,17:40:00,NaN,NaN,87.0,72.0,94.0,97.0
393,3,"[2016-10-22 18:00:00,2016-10-22 18:20:00)",1,2016-10-22 18:00:00,3-1,2016-10-22,1005.3,1010.3,0.0,6.0,...,95.0,0.0,5,18:00:00,NaN,NaN,NaN,87.0,72.0,94.0
394,3,"[2016-10-22 18:20:00,2016-10-22 18:40:00)",1,2016-10-22 18:20:00,3-1,2016-10-22,1005.3,1010.3,0.0,6.0,...,95.0,0.0,5,18:20:00,NaN,NaN,NaN,NaN,87.0,72.0
395,3,"[2016-10-22 18:40:00,2016-10-22 19:00:00)",1,2016-10-22 18:40:00,3-1,2016-10-22,1005.3,1010.3,0.0,6.0,...,95.0,0.0,5,18:40:00,NaN,NaN,NaN,NaN,NaN,87.0
396,3,"[2016-10-23 08:00:00,2016-10-23 08:20:00)",1,2016-10-23 08:00:00,3-1,2016-10-23,1009.1,1014.1,13.0,3.2,...,84.0,0.0,6,08:00:00,51.0,53.0,36.0,33.0,19.0,9.0
397,3,"[2016-10-23 08:20:00,2016-10-23 08:40:00)",1,2016-10-23 08:20:00,3-1,2016-10-23,1009.1,1014.1,13.0,3.2,...,84.0,0.0,6,08:20:00,NaN,51.0,53.0,36.0,33.0,19.0
398,3,"[2016-10-23 08:40:00,2016-10-23 09:00:00)",1,2016-10-23 08:40:00,3-1,2016-10-23,1009.1,1014.1,13.0,3.2,...,84.0,0.0,6,08:40:00,NaN,NaN,51.0,53.0,36.0,33.0
399,3,"[2016-10-23 09:00:00,2016-10-23 09:20:00)",1,2016-10-23 09:00:00,3-1,2016-10-23,1009.9,1014.9,344.0,1.9,...,87.0,0.0,6,09:00:00,NaN,NaN,NaN,51.0,53.0,36.0
400,3,"[2016-10-23 09:20:00,2016-10-23 09:40:00)",1,2016-10-23 09:20:00,3-1,2016-10-23,1009.9,1014.9,344.0,1.9,...,87.0,0.0,6,09:20:00,NaN,NaN,NaN,NaN,51.0,53.0
401,3,"[2016-10-23 09:40:00,2016-10-23 10:00:00)",1,2016-10-23 09:40:00,3-1,2016-10-23,1009.9,1014.9,344.0,1.9,...,87.0,0.0,6,09:40:00,NaN,NaN,NaN,NaN,NaN,51.0
402,3,"[2016-10-23 17:00:00,2016-10-23 17:20:00)",1,2016-10-23 17:00:00,3-1,2016-10-23,1011.4,1016.4,326.0,1.1,...,92.0,0.0,6,17:00:00,104.0,91.0,95.0,89.0,117.0,137.0
403,3,"[2016-10-23 17:20:00,2016-10-23 17:40:00)",1,2016-10-23 17:20:00,3-1,2016-10-23,1011.4,1016.4,326.0,1.1,...,92.0,0.0,6,17:20:00,NaN,104.0,91.0,95.0,89.0,117.0
404,3,"[2016-10-23 17:40:00,2016-10-23 18:00:00)",1,2016-10-23 17:40:00,3-1,2016-10-23,1011.4,1016.4,326.0,1.1,...,92.0,0.0,6,17:40:00,NaN,NaN,104.0,91.0,95.0,89.0
405,3,"[2016-10-23 18:00:00,2016-10-23 18:20:00)",1,2016-10-23 18:00:00,3-1,2016-10-23,1011.0,1016.0,43.0,0.8,...,92.0,0.0,6,18:00:00,NaN,NaN,NaN,104.0,91.0,95.0
406,3,"[2016-10-23 18:20:00,2016-10-23 18:40:00)",1,2016-10-23 18:20:00,3-1,2016-10-23,1011.0,1016.0,43.0,0.8,...,92.0,0.0,6,18:20:00,NaN,NaN,NaN,NaN,104.0,91.0
407,3,"[2016-10-23 18:40:00,2016-10-23 19:00:00)",1,2016-10-23 18:40:00,3-1,2016-10-23,1011.0,1016.0,43.0,0.8,...,92.0,0.0,6,18:40:00,NaN,NaN,NaN,NaN,NaN,104.0
408,3,"[2016-10-24 08:00:00,2016-10-24 08:20:00)",1,2016-10-24 08:00:00,3-1,2016-10-24,1007.7,1012.7,175.0,1.4,...,68.0,0.0,0,08:00:00,99.0,101.0,75.0,60.0,41.0,23.0
409,3,"[2016-10-24 08:20:00,2016-10-24 08:40:00)",1,2016-10-24 08:20:00,3-1,2016-10-24,1007.7,1012.7,175.0,1.4,...,68.0,0.0,0,08:20:00,NaN,99.0,101.0,75.0,60.0,41.0
410,3,"[2016-10-24 08:40:00,2016-10-24 09:00:00)",1,2016-10-24 08:40:00,3-1,2016-10-24,1007.7,1012.7,175.0,1.4,...,68.0,0.0,0,08:40:00,NaN,NaN,99.0,101.0,75.0,60.0
411,3,"[2016-10-24 09:00:00,2016-10-24 09:20:00)",1,2016-10-24 09:00:00,3-1,2016-10-24,1007.3,1012.3,133.0,0.9,...,79.0,0.0,0,09:00:00,NaN,NaN,NaN,99.0,101.0,75.0
412,3,"[2016-10-24 09:20:00,2016-10-24 09:40:00)",1,2016-10-24 09:20:00,3-1,2016-10-24,1007.3,1012.3,133.0,0.9,...,79.0,0.0,0,09:20:00,NaN,NaN,NaN,NaN,99.0,101.0
413,3,"[2016-10-24 09:40:00,2016-10-24 10:00:00)",1,2016-10-24 09:40:00,3-1,2016-10-24,1007.3,1012.3,133.0,0.9,...,79.0,0.0,0,09:40:00,NaN,NaN,NaN,NaN,NaN,99.0
414,3,"[2016-10-24 17:00:00,2016-10-24 17:20:00)",1,2016-10-24 17:00:00,3-1,2016-10-24,1008.0,1013.0,210.0,1.4,...,91.0,0.0,0,17:00:00,81.0,80.0,101.0,71.0,102.0,80.0
415,3,"[2016-10-24 17:20:00,2016-10-24 17:40:00)",1,2016-10-24 17:20:00,3-1,2016-10-24,1008.0,1013.0,210.0,1.4,...,91.0,0.0,0,17:20:00,NaN,81.0,80.0,101.0,71.0,102.0
416,3,"[2016-10-24 17:40:00,2016-10-24 18:00:00)",1,2016-10-24 17:40:00,3-1,2016-10-24,1008.0,1013.0,210.0,1.4,...,91.0,0.0,0,17:40:00,NaN,NaN,81.0,80.0,101.0,71.0
417,3,"[2016-10-24 18:00:00,2016-10-24 18:20:00)",1,2016-10-24 18:00:00,3-1,2016-10-24,1007.3,1012.3,226.0,3.0,...,94.0,0.0,0,18:00:00,NaN,NaN,NaN,81.0,80.0,101.0
418,3,"[2016-10-24 18:20:00,2016-10-24 18:40:00)",1,2016-10-24 18:20:00,3-1,2016-10-24,1007.3,1012.3,226.0,3.0,...,94.0,0.0,0,18:20:00,NaN,NaN,NaN,NaN,81.0,80.0
419,3,"[2016-10-24 18:40:00,2016-10-24 19:00:00)",1,2016-10-24 18:40:00,3-1,2016-10-24,1007.3,1012.3,226.0,3.0,...,94.0,0.0,0,18:40:00,NaN,NaN,NaN,NaN,NaN,81.0

In [24]:
# timemap特征
# 把time映射成1～72
from collections import defaultdict
time_start = datetime(2016,10,17,0,0,0)
timedic = defaultdict(int)
for i in range(72):
    timedic[time_start.time()] = i+1
    time_start = time_start + timedelta(minutes=20)
test_volume['timemap'] = test_volume['time'].map(lambda x:timedic[x])

In [25]:
# 写出数据
test_volume.to_csv('test_volume_feature_ffill.csv', index=False)