# KDDCUP Data Extract

2017-05-11

### 录入数据

In [1]:
import numpy as np
import pandas as pd
from datetime import datetime,timedelta,date,time
import copy

In [2]:
# 读入平均时间，流量和天气数据（平均时间和流量由aggregate_travel_time.py和aggregate_volume.py生成）
in_file_path = '/home/godcedric/GitLocal/KDDCUP2017/result/training_20min_avg_travel_time.csv'
raw_data = pd.read_csv(in_file_path)
in_file_path = '/home/godcedric/GitLocal/KDDCUP2017/result/training_20min_avg_volume.csv'
raw_data2 = pd.read_csv(in_file_path)
in_file_path = '/home/godcedric/GitLocal/KDDCUP2017/result/weather (table 7)_training_update.csv'
weather_data = pd.read_csv(in_file_path)

In [3]:
# 训练集缺失值补充，保证每一个时间段都有数据
full_time = pd.read_csv('full_time.csv')
full_time = full_time.sort(['intersection_id','tollgate_id'])
raw_data = pd.merge(full_time, raw_data, on=['intersection_id','tollgate_id','time_window'], how='left')
ffill = lambda g:g.fillna(method='ffill')
bfill = lambda g:g.fillna(method='bfill')

raw_data['avg_travel_time'] = raw_data.groupby(['intersection_id','tollgate_id'])['avg_travel_time'].apply(ffill)
raw_data['avg_travel_time'] = raw_data.groupby(['intersection_id','tollgate_id'])['avg_travel_time'].apply(bfill)

full_time2 = pd.read_csv('full_time2.csv')
full_time2 = full_time2.sort(['tollgate_id','direction'])
raw_data2 = pd.merge(full_time2, raw_data2, on=['tollgate_id','time_window','direction'], how='left')
raw_data2['volume'] = raw_data2.groupby(['tollgate_id','direction'])['volume'].apply(ffill)
raw_data2['volume'] = raw_data2.groupby(['tollgate_id','direction'])['volume'].apply(bfill)

/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:3: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  app.launch_new_instance()
/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:12: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [4]:
raw_data2

,tollgate_id,time_window,direction,volume,etc
0,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13.0,4.0
1,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6.0,1.0
2,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9.0,1.0
3,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10.0,1.0
4,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14.0,3.0
5,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10.0,0.0
6,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7.0,1.0
7,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10.0,1.0
8,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6.0,0.0
9,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9.0,0.0
10,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4.0,1.0
11,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9.0,2.0
12,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10.0,0.0
13,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13.0,0.0
14,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12.0,0.0
15,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2.0,0.0
16,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8.0,2.0
17,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13.0,2.0
18,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8.0,2.0
19,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13.0,5.0
20,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32.0,9.0
21,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39.0,10.0
22,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31.0,11.0
23,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43.0,16.0
24,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46.0,17.0
25,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56.0,17.0
26,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41.0,9.0
27,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50.0,18.0
28,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49.0,10.0
29,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44.0,3.0
...,...,...,...,...,...
10410,3,"[2016-10-17 14:00:00,2016-10-17 14:20:00)",1,75.0,17.0
10411,3,"[2016-10-17 14:20:00,2016-10-17 14:40:00)",1,83.0,17.0
10412,3,"[2016-10-17 14:40:00,2016-10-17 15:00:00)",1,100.0,23.0
10413,3,"[2016-10-17 15:00:00,2016-10-17 15:20:00)",1,93.0,18.0
10414,3,"[2016-10-17 15:20:00,2016-10-17 15:40:00)",1,122.0,30.0
10415,3,"[2016-10-17 15:40:00,2016-10-17 16:00:00)",1,90.0,18.0
10416,3,"[2016-10-17 16:00:00,2016-10-17 16:20:00)",1,91.0,19.0
10417,3,"[2016-10-17 16:20:00,2016-10-17 16:40:00)",1,94.0,24.0
10418,3,"[2016-10-17 16:40:00,2016-10-17 17:00:00)",1,90.0,19.0
10419,3,"[2016-10-17 17:00:00,2016-10-17 17:20:00)",1,80.0,31.0
10420,3,"[2016-10-17 17:20:00,2016-10-17 17:40:00)",1,82.0,22.0
10421,3,"[2016-10-17 17:40:00,2016-10-17 18:00:00)",1,84.0,30.0
10422,3,"[2016-10-17 18:00:00,2016-10-17 18:20:00)",1,79.0,28.0
10423,3,"[2016-10-17 18:20:00,2016-10-17 18:40:00)",1,86.0,19.0
10424,3,"[2016-10-17 18:40:00,2016-10-17 19:00:00)",1,80.0,18.0
10425,3,"[2016-10-17 19:00:00,2016-10-17 19:20:00)",1,54.0,22.0
10426,3,"[2016-10-17 19:20:00,2016-10-17 19:40:00)",1,47.0,15.0
10427,3,"[2016-10-17 19:40:00,2016-10-17 20:00:00)",1,54.0,14.0
10428,3,"[2016-10-17 20:00:00,2016-10-17 20:20:00)",1,51.0,19.0
10429,3,"[2016-10-17 20:20:00,2016-10-17 20:40:00)",1,25.0,12.0
10430,3,"[2016-10-17 20:40:00,2016-10-17 21:00:00)",1,43.0,13.0
10431,3,"[2016-10-17 21:00:00,2016-10-17 21:20:00)",1,23.0,8.0
10432,3,"[2016-10-17 21:20:00,2016-10-17 21:40:00)",1,25.0,7.0
10433,3,"[2016-10-17 21:40:00,2016-10-17 22:00:00)",1,22.0,5.0
10434,3,"[2016-10-17 22:00:00,2016-10-17 22:20:00)",1,16.0,5.0
10435,3,"[2016-10-17 22:20:00,2016-10-17 22:40:00)",1,18.0,5.0
10436,3,"[2016-10-17 22:40:00,2016-10-17 23:00:00)",1,28.0,12.0
10437,3,"[2016-10-17 23:00:00,2016-10-17 23:20:00)",1,9.0,2.0
10438,3,"[2016-10-17 23:20:00,2016-10-17 23:40:00)",1,12.0,3.0
10439,3,"[2016-10-17 23:40:00,2016-10-18 00:00:00)",1,22.0,1.0

### 提取平均时间数据

In [5]:
# 整合平均时间与天气数据
raw_data['start_time'] = raw_data['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:], '%Y-%m-%d %H:%M:%S'))
weather_data['date'] = weather_data['date'].astype(str)
weather_data['hour'] = weather_data['hour'].map(lambda x: ' ' + time(x, 0, 0).strftime('%H:%M:%S'))
weather_data['start_time'] = weather_data['date'] + weather_data['hour']
weather_data['start_time'] = weather_data['start_time'].map(lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S'))
num = len(weather_data)
for i in range(num):
    temp = weather_data.ix[i]
    temp1 = copy.deepcopy(temp)
    temp2 = copy.deepcopy(temp)
    temp3 = copy.deepcopy(temp)
    temp4 = copy.deepcopy(temp)
    temp5 = copy.deepcopy(temp)
    temp6 = copy.deepcopy(temp)
    temp7 = copy.deepcopy(temp)
    temp8 = copy.deepcopy(temp)
    stime = temp.start_time
    temp1.start_time = stime + timedelta(minutes=20)
    temp2.start_time = stime + timedelta(minutes=40)
    temp3.start_time = stime + timedelta(minutes=60)
    temp4.start_time = stime + timedelta(minutes=80)
    temp5.start_time = stime + timedelta(minutes=100)
    temp6.start_time = stime + timedelta(minutes=120)
    temp7.start_time = stime + timedelta(minutes=140)
    temp8.start_time = stime + timedelta(minutes=160)
    alltemp = [temp1, temp2, temp3, temp4, temp5, temp6, temp7, temp8]
    alltemp = pd.DataFrame(alltemp)
    weather_data = pd.concat([weather_data, alltemp])
weather_data.sort('start_time')

process_data = pd.merge(raw_data, weather_data, on='start_time', how='left')
del process_data['hour']
process_data['time'] = process_data['start_time'].map(lambda x: x.time())

/home/godcedric/anaconda3/lib/python3.6/site-packages/ipykernel/__main__.py:30: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)

In [6]:
# 增加路线和星期几特征
process_data['weekday'] = process_data['start_time'].map(lambda x: x.weekday())
process_data['route'] = process_data['intersection_id'].astype(str) + '-' + process_data['tollgate_id'].astype(str)

In [7]:
process_data

,intersection_id,tollgate_id,time_window,avg_travel_time,start_time,date,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,time,weekday,route
0,A,2,"[2016-07-19 00:00:00,2016-07-19 00:20:00)",58.05,2016-07-19 00:00:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,00:00:00,1,A-2
1,A,2,"[2016-07-19 00:20:00,2016-07-19 00:40:00)",58.05,2016-07-19 00:20:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,00:20:00,1,A-2
2,A,2,"[2016-07-19 00:40:00,2016-07-19 01:00:00)",58.05,2016-07-19 00:40:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,00:40:00,1,A-2
3,A,2,"[2016-07-19 01:00:00,2016-07-19 01:20:00)",58.05,2016-07-19 01:00:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,01:00:00,1,A-2
4,A,2,"[2016-07-19 01:20:00,2016-07-19 01:40:00)",56.87,2016-07-19 01:20:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,01:20:00,1,A-2
5,A,2,"[2016-07-19 01:40:00,2016-07-19 02:00:00)",77.74,2016-07-19 01:40:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,01:40:00,1,A-2
6,A,2,"[2016-07-19 02:00:00,2016-07-19 02:20:00)",77.74,2016-07-19 02:00:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,02:00:00,1,A-2
7,A,2,"[2016-07-19 02:20:00,2016-07-19 02:40:00)",42.64,2016-07-19 02:20:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,02:20:00,1,A-2
8,A,2,"[2016-07-19 02:40:00,2016-07-19 03:00:00)",40.17,2016-07-19 02:40:00,2016-07-19,1000.9,1005.8,219.0,3.3,27.5,81.0,0.0,02:40:00,1,A-2
9,A,2,"[2016-07-19 03:00:00,2016-07-19 03:20:00)",40.17,2016-07-19 03:00:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,03:00:00,1,A-2
10,A,2,"[2016-07-19 03:20:00,2016-07-19 03:40:00)",41.92,2016-07-19 03:20:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,03:20:00,1,A-2
11,A,2,"[2016-07-19 03:40:00,2016-07-19 04:00:00)",39.43,2016-07-19 03:40:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,03:40:00,1,A-2
12,A,2,"[2016-07-19 04:00:00,2016-07-19 04:20:00)",48.13,2016-07-19 04:00:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:00:00,1,A-2
13,A,2,"[2016-07-19 04:20:00,2016-07-19 04:40:00)",62.11,2016-07-19 04:20:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:20:00,1,A-2
14,A,2,"[2016-07-19 04:40:00,2016-07-19 05:00:00)",46.12,2016-07-19 04:40:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,04:40:00,1,A-2
15,A,2,"[2016-07-19 05:00:00,2016-07-19 05:20:00)",49.56,2016-07-19 05:00:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,05:00:00,1,A-2
16,A,2,"[2016-07-19 05:20:00,2016-07-19 05:40:00)",54.84,2016-07-19 05:20:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,05:20:00,1,A-2
17,A,2,"[2016-07-19 05:40:00,2016-07-19 06:00:00)",58.08,2016-07-19 05:40:00,2016-07-19,1000.5,1005.3,212.0,3.8,31.7,65.0,0.0,05:40:00,1,A-2
18,A,2,"[2016-07-19 06:00:00,2016-07-19 06:20:00)",46.36,2016-07-19 06:00:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:00:00,1,A-2
19,A,2,"[2016-07-19 06:20:00,2016-07-19 06:40:00)",48.59,2016-07-19 06:20:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:20:00,1,A-2
20,A,2,"[2016-07-19 06:40:00,2016-07-19 07:00:00)",66.64,2016-07-19 06:40:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,06:40:00,1,A-2
21,A,2,"[2016-07-19 07:00:00,2016-07-19 07:20:00)",64.68,2016-07-19 07:00:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:00:00,1,A-2
22,A,2,"[2016-07-19 07:20:00,2016-07-19 07:40:00)",85.68,2016-07-19 07:20:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:20:00,1,A-2
23,A,2,"[2016-07-19 07:40:00,2016-07-19 08:00:00)",58.97,2016-07-19 07:40:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,07:40:00,1,A-2
24,A,2,"[2016-07-19 08:00:00,2016-07-19 08:20:00)",81.60,2016-07-19 08:00:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:00:00,1,A-2
25,A,2,"[2016-07-19 08:20:00,2016-07-19 08:40:00)",80.21,2016-07-19 08:20:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:20:00,1,A-2
26,A,2,"[2016-07-19 08:40:00,2016-07-19 09:00:00)",63.45,2016-07-19 08:40:00,2016-07-19,999.7,1004.5,239.0,1.9,31.8,64.0,0.0,08:40:00,1,A-2
27,A,2,"[2016-07-19 09:00:00,2016-07-19 09:20:00)",78.05,2016-07-19 09:00:00,2016-07-19,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:00:00,1,A-2
28,A,2,"[2016-07-19 09:20:00,2016-07-19 09:40:00)",69.04,2016-07-19 09:20:00,2016-07-19,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:20:00,1,A-2
29,A,2,"[2016-07-19 09:40:00,2016-07-19 10:00:00)",69.66,2016-07-19 09:40:00,2016-07-19,998.7,1003.5,218.0,2.0,31.5,69.0,0.0,09:40:00,1,A-2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39282,C,3,"[2016-10-17 14:00:00,2016-10-17 14:20:00)",149.21,2016-10-17 14:00:00,2016-10-17,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,14:00:00,0,C-3
39283,C,3,"[2016-10-17 14:20:00,2016-10-17 14:40:00)",150.72,2016-10-17 14:20:00,2016-10-17,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,14:20:00,0,C-3
39284,C,3,"[2016-10-17 14:40:00,2016-10-17 15:00:00)",191.02,2016-10-17 14:40:00,2016-10-17,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,14:40:00,0,C-3
39285,C,3,"[2016-10-17 15:00:00,2016-10-17 15:20:00)",126.44,2016-10-17 15:00:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,15:00:00,0,C-3
39286,C,3,"[2016-10-17 15:20:00,2016-10-17 15:40:00)",126.44,2016-10-17 15:20:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,15:20:00,0,C-3
39287,C,3,"[2016-10-17 15:40:00,2016-10-17 16:00:00)",126.44,2016-10-17 15:40:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,15:40:00,0,C-3
39288,C,3,"[2016-10-17 16:00:00,2016-10-17 16:20:00)",171.02,2016-10-17 16:00:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,16:00:00,0,C-3
39289,C,3,"[2016-10-17 16:20:00,2016-10-17 16:40:00)",311.18,2016-10-17 16:20:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,16:20:00,0,C-3
39290,C,3,"[2016-10-17 16:40:00,2016-10-17 17:00:00)",198.46,2016-10-17 16:40:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,16:40:00,0,C-3
39291,C,3,"[2016-10-17 17:00:00,2016-10-17 17:20:00)",198.46,2016-10-17 17:00:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,17:00:00,0,C-3
39292,C,3,"[2016-10-17 17:20:00,2016-10-17 17:40:00)",122.02,2016-10-17 17:20:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,17:20:00,0,C-3
39293,C,3,"[2016-10-17 17:40:00,2016-10-17 18:00:00)",122.02,2016-10-17 17:40:00,2016-10-17,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,17:40:00,0,C-3
39294,C,3,"[2016-10-17 18:00:00,2016-10-17 18:20:00)",173.74,2016-10-17 18:00:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,18:00:00,0,C-3
39295,C,3,"[2016-10-17 18:20:00,2016-10-17 18:40:00)",173.74,2016-10-17 18:20:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,18:20:00,0,C-3
39296,C,3,"[2016-10-17 18:40:00,2016-10-17 19:00:00)",526.49,2016-10-17 18:40:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,18:40:00,0,C-3
39297,C,3,"[2016-10-17 19:00:00,2016-10-17 19:20:00)",101.73,2016-10-17 19:00:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,19:00:00,0,C-3
39298,C,3,"[2016-10-17 19:20:00,2016-10-17 19:40:00)",101.73,2016-10-17 19:20:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,19:20:00,0,C-3
39299,C,3,"[2016-10-17 19:40:00,2016-10-17 20:00:00)",187.43,2016-10-17 19:40:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,19:40:00,0,C-3
39300,C,3,"[2016-10-17 20:00:00,2016-10-17 20:20:00)",209.32,2016-10-17 20:00:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,20:00:00,0,C-3
39301,C,3,"[2016-10-17 20:20:00,2016-10-17 20:40:00)",209.32,2016-10-17 20:20:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,20:20:00,0,C-3
39302,C,3,"[2016-10-17 20:40:00,2016-10-17 21:00:00)",194.49,2016-10-17 20:40:00,2016-10-17,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,20:40:00,0,C-3
39303,C,3,"[2016-10-17 21:00:00,2016-10-17 21:20:00)",195.00,2016-10-17 21:00:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:00:00,0,C-3
39304,C,3,"[2016-10-17 21:20:00,2016-10-17 21:40:00)",159.44,2016-10-17 21:20:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:20:00,0,C-3
39305,C,3,"[2016-10-17 21:40:00,2016-10-17 22:00:00)",159.44,2016-10-17 21:40:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,21:40:00,0,C-3
39306,C,3,"[2016-10-17 22:00:00,2016-10-17 22:20:00)",159.44,2016-10-17 22:00:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:00:00,0,C-3
39307,C,3,"[2016-10-17 22:20:00,2016-10-17 22:40:00)",185.25,2016-10-17 22:20:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:20:00,0,C-3
39308,C,3,"[2016-10-17 22:40:00,2016-10-17 23:00:00)",150.53,2016-10-17 22:40:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,22:40:00,0,C-3
39309,C,3,"[2016-10-17 23:00:00,2016-10-17 23:20:00)",150.53,2016-10-17 23:00:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,23:00:00,0,C-3
39310,C,3,"[2016-10-17 23:20:00,2016-10-17 23:40:00)",150.53,2016-10-17 23:20:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,23:20:00,0,C-3
39311,C,3,"[2016-10-17 23:40:00,2016-10-18 00:00:00)",150.53,2016-10-17 23:40:00,2016-10-17,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,23:40:00,0,C-3

In [9]:
# 增加前20分钟平均时间特征
start_time = process_data['start_time']
avg_travel_time = process_data['avg_travel_time']

In [6]:
last_20min = process_data['avg_travel_time'].copy() 
last_40min = process_data['avg_travel_time'].copy()
last_60min = process_data['avg_travel_time'].copy()
last_80min = process_data['avg_travel_time'].copy()
last_100min = process_data['avg_travel_time'].copy()
last_120min = process_data['avg_travel_time'].copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(start_time)):
    cur_time = start_time[i] #当前时间
    # 前20min
    if (i-1) >= 0:
        last20 = cur_time - timedelta(minutes=20)
        if last20 == start_time[i-1]:
            last_20min[i] = avg_travel_time[i-1]
    # 前40min
    if (i-2) >= 0:
        last40 = cur_time - timedelta(minutes=40)
        for j in range(2):
            if last40 == start_time[i-j-1]:
                last_40min[i] = avg_travel_time[i-j-1]
                break
    # 前60min
    if (i-3) >= 0:
        last60 = cur_time - timedelta(minutes=60)
        for j in range(3):
            if last60 == start_time[i-j-1]:
                last_60min[i] = avg_travel_time[i-j-1]
                break
    # 前80min
    if (i-4) >= 0:
        last80 = cur_time - timedelta(minutes=80)
        for j in range(4):
            if last80 == start_time[i-j-1]:
                last_80min[i] = avg_travel_time[i-j-1]
                break
    # 前100min
    if (i-5) >= 0:
        last100 = cur_time - timedelta(minutes=100)
        for j in range(5):
            if last100 == start_time[i-j-1]:
                last_100min[i] = avg_travel_time[i-j-1]
                break
    # 前120min
    if (i-6) >= 0:
        last120 = cur_time - timedelta(minutes=120)
        for j in range(6):
            if last120 == start_time[i-j-1]:
                last_120min[i] = avg_travel_time[i-j-1]
                break

process_data['last_20min'] = last_20min
process_data['last_40min'] = last_40min
process_data['last_60min'] = last_60min
process_data['last_80min'] = last_80min
process_data['last_100min'] = last_100min
process_data['last_120min'] = last_120min

In [8]:
# 把time映射成1～72
from collections import defaultdict
time_start = datetime(2016,10,17,0,0,0)
timedic = defaultdict(int)
for i in range(72):
    timedic[time_start.time()] = i+1
    time_start = time_start + timedelta(minutes=20)

In [9]:
process_data['timemap'] = process_data['time'].map(lambda x:timedic[x])

In [10]:
# 增加法定节假日特征
holiday = ['2016-09-15','2016-09-16','2016-09-17','2016-10-01','2016-10-02','2016-10-03','2016-10-04','2016-10-05','2016-10-06','2016-10-07']
def ff(x):
    if x in holiday:
        return 1
    else:
        return 0
process_data['holiday'] = process_data['date'].map(ff)

In [14]:
# 把速度列加上去
#avg_speed = pd.read_csv('avg_speed_all_route_and_last_link.csv')
#process_data['avg_all_route_speed'] = list(avg_speed['avg_all_route_speed'])
#process_data['avg_last_link_speed'] = list(avg_speed['avg_last_link_speed'])

In [11]:
# 写出数据
process_data.to_csv('travel_time_raw_data_ffill.csv', index=False)

### 提取流量数据

In [12]:
# 整合流量与天气数据
raw_data2['start_time'] = raw_data2['time_window'].map(lambda x: datetime.strptime(x.split(',')[0][1:],'%Y-%m-%d %H:%M:%S'))
raw_data2['pair'] = raw_data2['tollgate_id'].astype(str) + '-' + raw_data2['direction'].astype(str)
process_data2 = pd.merge(raw_data2, weather_data, on='start_time', how='left')

In [13]:
# 增加星期几和时间窗口两列
process_data2['weekday'] = process_data2['start_time'].map(lambda x: x.weekday())
process_data2['time'] = process_data2['start_time'].map(lambda x: x.time())

In [21]:
# 增加前20分钟流量特征
start_time = process_data2['start_time']
volume = process_data2['volume']

In [23]:
last_20min = process_data2['volume'].copy() 
last_40min = process_data2['volume'].copy()
last_60min = process_data2['volume'].copy()
last_80min = process_data2['volume'].copy()
last_100min = process_data2['volume'].copy()
last_120min = process_data2['volume'].copy()
last_20min[:] = np.nan
last_40min[:] = np.nan
last_60min[:] = np.nan
last_80min[:] = np.nan
last_100min[:] = np.nan
last_120min[:] = np.nan
for i in range(len(start_time)):
    cur_time = start_time[i] #当前时间
    # 前20min
    if (i-1) >= 0:
        last20 = cur_time - timedelta(minutes=20)
        if last20 == start_time[i-1]:
            last_20min[i] = volume[i-1]
    # 前40min
    if (i-2) >= 0:
        last40 = cur_time - timedelta(minutes=40)
        for j in range(2):
            if last40 == start_time[i-j-1]:
                last_40min[i] = volume[i-j-1]
                break
    # 前60min
    if (i-3) >= 0:
        last60 = cur_time - timedelta(minutes=60)
        for j in range(3):
            if last60 == start_time[i-j-1]:
                last_60min[i] = volume[i-j-1]
                break
    # 前80min
    if (i-4) >= 0:
        last80 = cur_time - timedelta(minutes=80)
        for j in range(4):
            if last80 == start_time[i-j-1]:
                last_80min[i] = volume[i-j-1]
                break
    # 前100min
    if (i-5) >= 0:
        last100 = cur_time - timedelta(minutes=100)
        for j in range(5):
            if last100 == start_time[i-j-1]:
                last_100min[i] = volume[i-j-1]
                break
    # 前120min
    if (i-6) >= 0:
        last120 = cur_time - timedelta(minutes=120)
        for j in range(6):
            if last120 == start_time[i-j-1]:
                last_120min[i] = volume[i-j-1]
                break

process_data2['last_20min'] = last_20min
process_data2['last_40min'] = last_40min
process_data2['last_60min'] = last_60min
process_data2['last_80min'] = last_80min
process_data2['last_100min'] = last_100min
process_data2['last_120min'] = last_120min

In [14]:
process_data2

,tollgate_id,time_window,direction,volume,etc,start_time,pair,date,hour,pressure,sea_pressure,wind_direction,wind_speed,temperature,rel_humidity,precipitation,weekday,time
0,1,"[2016-09-19 00:00:00,2016-09-19 00:20:00)",0,13.0,4.0,2016-09-19 00:00:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,00:00:00
1,1,"[2016-09-19 00:20:00,2016-09-19 00:40:00)",0,6.0,1.0,2016-09-19 00:20:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,00:20:00
2,1,"[2016-09-19 00:40:00,2016-09-19 01:00:00)",0,9.0,1.0,2016-09-19 00:40:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,00:40:00
3,1,"[2016-09-19 01:00:00,2016-09-19 01:20:00)",0,10.0,1.0,2016-09-19 01:00:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,01:00:00
4,1,"[2016-09-19 01:20:00,2016-09-19 01:40:00)",0,14.0,3.0,2016-09-19 01:20:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,01:20:00
5,1,"[2016-09-19 01:40:00,2016-09-19 02:00:00)",0,10.0,0.0,2016-09-19 01:40:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,01:40:00
6,1,"[2016-09-19 02:00:00,2016-09-19 02:20:00)",0,7.0,1.0,2016-09-19 02:00:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,02:00:00
7,1,"[2016-09-19 02:20:00,2016-09-19 02:40:00)",0,10.0,1.0,2016-09-19 02:20:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,02:20:00
8,1,"[2016-09-19 02:40:00,2016-09-19 03:00:00)",0,6.0,0.0,2016-09-19 02:40:00,1-0,2016-09-19,00:00:00,1008.2,1013.2,329.0,2.8,22.2,76.0,0.0,0,02:40:00
9,1,"[2016-09-19 03:00:00,2016-09-19 03:20:00)",0,9.0,0.0,2016-09-19 03:00:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,03:00:00
10,1,"[2016-09-19 03:20:00,2016-09-19 03:40:00)",0,4.0,1.0,2016-09-19 03:20:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,03:20:00
11,1,"[2016-09-19 03:40:00,2016-09-19 04:00:00)",0,9.0,2.0,2016-09-19 03:40:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,03:40:00
12,1,"[2016-09-19 04:00:00,2016-09-19 04:20:00)",0,10.0,0.0,2016-09-19 04:00:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,04:00:00
13,1,"[2016-09-19 04:20:00,2016-09-19 04:40:00)",0,13.0,0.0,2016-09-19 04:20:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,04:20:00
14,1,"[2016-09-19 04:40:00,2016-09-19 05:00:00)",0,12.0,0.0,2016-09-19 04:40:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,04:40:00
15,1,"[2016-09-19 05:00:00,2016-09-19 05:20:00)",0,2.0,0.0,2016-09-19 05:00:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,05:00:00
16,1,"[2016-09-19 05:20:00,2016-09-19 05:40:00)",0,8.0,2.0,2016-09-19 05:20:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,05:20:00
17,1,"[2016-09-19 05:40:00,2016-09-19 06:00:00)",0,13.0,2.0,2016-09-19 05:40:00,1-0,2016-09-19,03:00:00,1008.3,1013.3,15.0,4.5,24.4,67.0,0.0,0,05:40:00
18,1,"[2016-09-19 06:00:00,2016-09-19 06:20:00)",0,8.0,2.0,2016-09-19 06:00:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,06:00:00
19,1,"[2016-09-19 06:20:00,2016-09-19 06:40:00)",0,13.0,5.0,2016-09-19 06:20:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,06:20:00
20,1,"[2016-09-19 06:40:00,2016-09-19 07:00:00)",0,32.0,9.0,2016-09-19 06:40:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,06:40:00
21,1,"[2016-09-19 07:00:00,2016-09-19 07:20:00)",0,39.0,10.0,2016-09-19 07:00:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,07:00:00
22,1,"[2016-09-19 07:20:00,2016-09-19 07:40:00)",0,31.0,11.0,2016-09-19 07:20:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,07:20:00
23,1,"[2016-09-19 07:40:00,2016-09-19 08:00:00)",0,43.0,16.0,2016-09-19 07:40:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,07:40:00
24,1,"[2016-09-19 08:00:00,2016-09-19 08:20:00)",0,46.0,17.0,2016-09-19 08:00:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,08:00:00
25,1,"[2016-09-19 08:20:00,2016-09-19 08:40:00)",0,56.0,17.0,2016-09-19 08:20:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,08:20:00
26,1,"[2016-09-19 08:40:00,2016-09-19 09:00:00)",0,41.0,9.0,2016-09-19 08:40:00,1-0,2016-09-19,06:00:00,1007.4,1012.3,12.0,6.2,26.8,56.0,0.0,0,08:40:00
27,1,"[2016-09-19 09:00:00,2016-09-19 09:20:00)",0,50.0,18.0,2016-09-19 09:00:00,1-0,2016-09-19,09:00:00,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1,0,09:00:00
28,1,"[2016-09-19 09:20:00,2016-09-19 09:40:00)",0,49.0,10.0,2016-09-19 09:20:00,1-0,2016-09-19,09:00:00,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1,0,09:20:00
29,1,"[2016-09-19 09:40:00,2016-09-19 10:00:00)",0,44.0,3.0,2016-09-19 09:40:00,1-0,2016-09-19,09:00:00,1008.3,1013.3,351.0,5.3,23.8,72.0,0.1,0,09:40:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10410,3,"[2016-10-17 14:00:00,2016-10-17 14:20:00)",1,75.0,17.0,2016-10-17 14:00:00,3-1,2016-10-17,12:00:00,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,0,14:00:00
10411,3,"[2016-10-17 14:20:00,2016-10-17 14:40:00)",1,83.0,17.0,2016-10-17 14:20:00,3-1,2016-10-17,12:00:00,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,0,14:20:00
10412,3,"[2016-10-17 14:40:00,2016-10-17 15:00:00)",1,100.0,23.0,2016-10-17 14:40:00,3-1,2016-10-17,12:00:00,1014.3,1019.4,17.0,0.7,19.6,87.0,0.0,0,14:40:00
10413,3,"[2016-10-17 15:00:00,2016-10-17 15:20:00)",1,93.0,18.0,2016-10-17 15:00:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,15:00:00
10414,3,"[2016-10-17 15:20:00,2016-10-17 15:40:00)",1,122.0,30.0,2016-10-17 15:20:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,15:20:00
10415,3,"[2016-10-17 15:40:00,2016-10-17 16:00:00)",1,90.0,18.0,2016-10-17 15:40:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,15:40:00
10416,3,"[2016-10-17 16:00:00,2016-10-17 16:20:00)",1,91.0,19.0,2016-10-17 16:00:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,16:00:00
10417,3,"[2016-10-17 16:20:00,2016-10-17 16:40:00)",1,94.0,24.0,2016-10-17 16:20:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,16:20:00
10418,3,"[2016-10-17 16:40:00,2016-10-17 17:00:00)",1,90.0,19.0,2016-10-17 16:40:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,16:40:00
10419,3,"[2016-10-17 17:00:00,2016-10-17 17:20:00)",1,80.0,31.0,2016-10-17 17:00:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,17:00:00
10420,3,"[2016-10-17 17:20:00,2016-10-17 17:40:00)",1,82.0,22.0,2016-10-17 17:20:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,17:20:00
10421,3,"[2016-10-17 17:40:00,2016-10-17 18:00:00)",1,84.0,30.0,2016-10-17 17:40:00,3-1,2016-10-17,15:00:00,1014.7,1019.8,222.0,0.9,18.9,92.0,0.0,0,17:40:00
10422,3,"[2016-10-17 18:00:00,2016-10-17 18:20:00)",1,79.0,28.0,2016-10-17 18:00:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,18:00:00
10423,3,"[2016-10-17 18:20:00,2016-10-17 18:40:00)",1,86.0,19.0,2016-10-17 18:20:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,18:20:00
10424,3,"[2016-10-17 18:40:00,2016-10-17 19:00:00)",1,80.0,18.0,2016-10-17 18:40:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,18:40:00
10425,3,"[2016-10-17 19:00:00,2016-10-17 19:20:00)",1,54.0,22.0,2016-10-17 19:00:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,19:00:00
10426,3,"[2016-10-17 19:20:00,2016-10-17 19:40:00)",1,47.0,15.0,2016-10-17 19:20:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,19:20:00
10427,3,"[2016-10-17 19:40:00,2016-10-17 20:00:00)",1,54.0,14.0,2016-10-17 19:40:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,19:40:00
10428,3,"[2016-10-17 20:00:00,2016-10-17 20:20:00)",1,51.0,19.0,2016-10-17 20:00:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,20:00:00
10429,3,"[2016-10-17 20:20:00,2016-10-17 20:40:00)",1,25.0,12.0,2016-10-17 20:20:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,20:20:00
10430,3,"[2016-10-17 20:40:00,2016-10-17 21:00:00)",1,43.0,13.0,2016-10-17 20:40:00,3-1,2016-10-17,18:00:00,1014.0,1019.0,341.0,1.5,19.1,92.0,0.0,0,20:40:00
10431,3,"[2016-10-17 21:00:00,2016-10-17 21:20:00)",1,23.0,8.0,2016-10-17 21:00:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,21:00:00
10432,3,"[2016-10-17 21:20:00,2016-10-17 21:40:00)",1,25.0,7.0,2016-10-17 21:20:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,21:20:00
10433,3,"[2016-10-17 21:40:00,2016-10-17 22:00:00)",1,22.0,5.0,2016-10-17 21:40:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,21:40:00
10434,3,"[2016-10-17 22:00:00,2016-10-17 22:20:00)",1,16.0,5.0,2016-10-17 22:00:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,22:00:00
10435,3,"[2016-10-17 22:20:00,2016-10-17 22:40:00)",1,18.0,5.0,2016-10-17 22:20:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,22:20:00
10436,3,"[2016-10-17 22:40:00,2016-10-17 23:00:00)",1,28.0,12.0,2016-10-17 22:40:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,22:40:00
10437,3,"[2016-10-17 23:00:00,2016-10-17 23:20:00)",1,9.0,2.0,2016-10-17 23:00:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,23:00:00
10438,3,"[2016-10-17 23:20:00,2016-10-17 23:40:00)",1,12.0,3.0,2016-10-17 23:20:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,23:20:00
10439,3,"[2016-10-17 23:40:00,2016-10-18 00:00:00)",1,22.0,1.0,2016-10-17 23:40:00,3-1,2016-10-17,21:00:00,1013.9,1018.9,322.0,2.5,19.3,90.0,0.0,0,23:40:00

In [15]:
# 时间映射成1～72
process_data2['timemap'] = process_data2['time'].map(lambda x:timedic[x])

In [16]:
process_data2['holiday'] = process_data2['date'].map(ff)

In [17]:
# 写出数据
process_data2.to_csv('volume_raw_data_ffill.csv', index=False)